import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-marketing-video-retention-secret",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

type VideoRow = {
  id: string;
  custom_thumbnail_path: string | null;
  status: string;
  delete_after: string | null;
};

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function isUuid(value: unknown): value is string {
  return typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
}

async function canManageVideos(
  userClient: ReturnType<typeof createClient>,
): Promise<boolean> {
  const { data, error } = await userClient.rpc("can_manage_marketing_videos");
  return !error && data === true;
}

async function removeOwnedThumbnail(
  admin: ReturnType<typeof createClient>,
  video: VideoRow,
): Promise<{ removed: boolean; shared: boolean; error: string | null }> {
  const path = video.custom_thumbnail_path?.trim() || "";
  // Only the upload namespace generated by uploadVideoThumbnail is eligible.
  if (!path || !path.startsWith("video-thumbnails/")) return { removed: false, shared: false, error: null };

  const { data: otherOwner, error: ownerError } = await admin
    .from("marketing_videos")
    .select("id")
    .eq("custom_thumbnail_path", path)
    .neq("id", video.id)
    .limit(1)
    .maybeSingle();
  if (ownerError) return { removed: false, shared: false, error: ownerError.message };
  if (otherOwner) return { removed: false, shared: true, error: null };

  const { error } = await admin.storage.from("news-assets").remove([path]);
  if (error) return { removed: false, shared: false, error: error.message };
  return { removed: true, shared: false, error: null };
}

async function permanentlyRemoveVideo(
  admin: ReturnType<typeof createClient>,
  videoId: string,
  requireExpired: boolean,
) {
  let query = admin
    .from("marketing_videos")
    .select("id, custom_thumbnail_path, status, delete_after")
    .eq("id", videoId)
    .eq("status", "archived");
  if (requireExpired) query = query.lte("delete_after", new Date().toISOString());

  const { data, error } = await query.maybeSingle();
  if (error) return { id: videoId, deleted: false, skipped: false, error: error.message };
  if (!data) return { id: videoId, deleted: false, skipped: true, error: null };
  const video = data as VideoRow;

  // Storage first: an error leaves the archived row and relations intact for retry.
  const thumbnail = await removeOwnedThumbnail(admin, video);
  if (thumbnail.error) return { id: videoId, deleted: false, skipped: false, error: `thumbnail_cleanup_failed: ${thumbnail.error}` };

  // These canonical video relations use ON DELETE CASCADE. Deleting the
  // parent keeps the relation cleanup atomic, so a recoverable archive never
  // loses mappings because an individual relation request partially failed.
  const { error: deleteError } = await admin.from("marketing_videos").delete().eq("id", videoId);
  if (deleteError) return { id: videoId, deleted: false, skipped: false, error: `video_delete_failed: ${deleteError.message}` };
  return { id: videoId, deleted: true, skipped: false, thumbnail_removed: thumbnail.removed, thumbnail_shared: thumbnail.shared, error: null };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

  const url = Deno.env.get("SUPABASE_URL");
  const serviceRole = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  const anonKey = Deno.env.get("SUPABASE_ANON_KEY");
  if (!url || !serviceRole || !anonKey) return json({ error: "Missing Supabase runtime credentials" }, 500);

  let body: { action?: unknown; video_id?: unknown };
  try {
    body = await req.json();
  } catch {
    return json({ error: "Invalid JSON body" }, 400);
  }

  const admin = createClient(url, serviceRole, { auth: { persistSession: false, autoRefreshToken: false } });

  if (body.action === "cleanup_expired") {
    const schedulerSecret = req.headers.get("x-marketing-video-retention-secret") || "";
    const { data: scheduled, error: secretError } = await admin.rpc("is_marketing_video_retention_scheduler", { p_secret: schedulerSecret });
    if (secretError || scheduled !== true) return json({ error: "Scheduler authentication failed" }, 401);

    const { data: rows, error } = await admin
      .from("marketing_videos")
      .select("id")
      .eq("status", "archived")
      .lte("delete_after", new Date().toISOString())
      .limit(100);
    if (error) return json({ error: error.message }, 500);

    const results = [];
    for (const row of rows ?? []) {
      results.push(await permanentlyRemoveVideo(admin, String(row.id), true));
    }
    return json({ processed: results.length, results });
  }

  if (body.action !== "delete_archived" || !isUuid(body.video_id)) {
    return json({ error: "Unsupported action" }, 400);
  }

  const authorization = req.headers.get("Authorization") || "";
  if (!authorization.toLowerCase().startsWith("bearer ")) return json({ error: "Authentication required" }, 401);
  const userClient = createClient(url, anonKey, {
    global: { headers: { Authorization: authorization } },
    auth: { persistSession: false, autoRefreshToken: false },
  });
  const { data: userData, error: userError } = await userClient.auth.getUser();
  if (userError || !userData.user) return json({ error: "Invalid session" }, 401);
  if (!await canManageVideos(userClient)) return json({ error: "Marketing video management access denied" }, 403);

  const result = await permanentlyRemoveVideo(admin, body.video_id, false);
  if (result.error) return json(result, 500);
  return json(result);
});
