import { useEffect } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowRight, BarChart3, CalendarDays, CheckCircle2, ChevronRight, CirclePlay, ClipboardList, Crown, Factory, Gem, GraduationCap, Lock, LockKeyhole, Map, Medal, Play, ShieldCheck, ShoppingCart, Trophy, Users } from 'lucide-react';
import PortalHeader from '@/components/portal/PortalHeader';
import { academySandbox } from '@/lib/academySandbox';
import { activateLocalAcademyEnrollment, getAcademyCapabilityProgress, getAcademyProgress, getLocalAcademyUser, isAcademyCapabilityUnlocked } from '@/lib/academyCurriculum';
import { useAppUser } from '@/context/AppUserContext';
import { useLanguage } from '@/context/LanguageContext';
import { cn } from '@/lib/utils';

type State = 'new' | 'active' | 'ready' | 'done' | 'locked';
const labels: Record<State, string> = { new: 'Ny', active: 'I gang', ready: 'Klar', done: 'Gennemført', locked: 'Låst' };
function ProgressBar({ value, gold = false }: { value: number; gold?: boolean }) { return <div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className={cn('h-full rounded-full', gold ? 'bg-amber-500' : 'bg-emerald-600')} style={{ width: `${Math.max(0, Math.min(value, 100))}%` }} /></div>; }
function Status({ state }: { state: State }) { return <span className={cn('inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold', state === 'new' && 'bg-sky-50 text-sky-700', state === 'active' && 'bg-amber-50 text-amber-800', state === 'ready' && 'bg-emerald-50 text-emerald-700', state === 'done' && 'bg-emerald-100 text-emerald-800', state === 'locked' && 'bg-slate-100 text-slate-500')}>{state === 'locked' ? <Lock className="h-3 w-3" /> : state === 'done' ? <CheckCircle2 className="h-3 w-3" /> : null}{labels[state]}</span>; }
function Module({ icon: Icon, title, progress, children }: { icon: typeof ShoppingCart; title: string; progress: string; children: React.ReactNode }) { return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><header className="flex items-center justify-between px-5 py-4"><div className="flex items-center gap-2.5"><Icon className="h-[18px] w-[18px] text-[#126a45]" /><h2 className="text-sm font-bold text-slate-900">{title}</h2></div><span className="text-xs font-medium text-slate-500">{progress}</span></header>{children}</section>; }
function AcademyRow({ image, title, description, state, action, onClick }: { image?: string; title: string; description: string; state: State; action?: string; onClick?: () => void }) { return <div className="grid grid-cols-[56px_minmax(0,1fr)_auto] items-center gap-3 border-t border-slate-100 px-4 py-3.5 sm:px-5"><div className="flex h-12 w-14 items-center justify-center overflow-hidden rounded-lg bg-slate-100">{image ? <img src={image} alt="" className="h-full w-full object-cover" /> : <ClipboardList className="h-5 w-5 text-slate-400" />}</div><div className="min-w-0"><div className="truncate text-sm font-semibold text-slate-900">{title}</div><p className="mt-0.5 line-clamp-2 text-xs leading-5 text-slate-500">{description}</p></div><div className="flex items-center gap-3"><Status state={state} />{action && <button type="button" onClick={onClick} className="hidden items-center gap-1 rounded-md bg-[#126a45] px-3 py-2 text-xs font-semibold text-white shadow-sm hover:bg-[#0f5a3b] sm:inline-flex">{action}<ArrowRight className="h-3.5 w-3.5" /></button>}<ChevronRight className="h-4 w-4 text-slate-400" /></div></div>; }
function Journey({ icon: Icon, label, active = false }: { icon: typeof ShoppingCart; label: string; active?: boolean }) { return <div className="flex min-w-0 flex-1 flex-col items-center text-center"><div className={cn('flex h-9 w-9 items-center justify-center rounded-full border', active ? 'border-emerald-700 bg-emerald-700 text-white' : 'border-slate-200 bg-slate-50 text-slate-400')}><Icon className="h-4 w-4" /></div><span className={cn('mt-2 max-w-16 text-[10px] font-semibold leading-3', active ? 'text-[#126a45]' : 'text-slate-500')}>{label}</span></div>; }

export default function AcademyPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const { appUser, setAppUser, logout } = useAppUser(); const { language, setLanguage } = useLanguage(); const task = academySandbox.getCase1();
  useEffect(() => { if (import.meta.env.DEV) { activateLocalAcademyEnrollment(); if (appUser?.id !== 'academy-local-sales-user') setAppUser(getLocalAcademyUser()); } }, [appUser, setAppUser]);
  const user = appUser || getLocalAcademyUser(); const completed = academySandbox.getCompletedCaseIds(); const progress = getAcademyProgress(user, completed); const configurator = getAcademyCapabilityProgress('configurator', completed); const unlocked = isAcademyCapabilityUnlocked(user, 'configurator', completed);
  const requirements = [task.machine, task.flail, task.weedBrush, task.requiredComponents, task.workLight, task.wireHarness, task.deliveryDiscount, task.quantityDiscount, task.quoteGenerated, Boolean(task.leadId)].filter(Boolean).length;
  const caseState: State = task.completed ? 'done' : task.started ? 'active' : 'new'; const startCase = () => { academySandbox.startCase1(); navigate('/configurator?academy_mode=true'); };
  const nav = [['Forside', '/portal', Factory], ['Min Academy', '/academy', GraduationCap], ['Salg', '/portal/sales', ShoppingCart], ['Partnerdata', '/portal/dealer-data', Users], ['CRM', '/portal/crm/leads', Users], ['Demo', '/portal/crm/demo-leads', CirclePlay], ['Tilbud & ordre', '/portal/crm/quotes', ClipboardList], ['Video', '/portal/videos', Play], ['Kalender', '/portal/crm/calendar', CalendarDays]] as const;
  return <div className="min-h-screen bg-slate-50"><PortalHeader user={user} language={language} onLanguageChange={setLanguage} onLogout={async () => { await logout(); navigate('/portal', { replace: true }); }} /><div className="mx-auto flex max-w-[1540px] border-x border-slate-200 bg-slate-50"><aside className="hidden w-60 shrink-0 flex-col bg-[#102c25] text-white lg:flex"><nav className="px-3 py-5"><div className="mb-5 px-3 text-[11px] font-semibold uppercase tracking-[0.16em] text-emerald-200/70">Portal</div>{nav.map(([label, to, Icon]) => { const active = label === 'Min Academy'; const locked = !active && ['CRM', 'Demo', 'Tilbud & ordre'].includes(label); return <Link key={label} to={to} className={cn('mb-1 flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition', active ? 'bg-emerald-700/70 text-white shadow-sm' : locked ? 'text-emerald-50/55 hover:bg-white/5' : 'text-emerald-50/85 hover:bg-white/10')}><Icon className="h-4 w-4" />{label}{locked && <Lock className="ml-auto h-3.5 w-3.5 opacity-80" />}</Link>; })}</nav><div className="mt-auto border-t border-white/10 p-5"><p className="max-w-32 text-sm font-medium leading-6 text-white/90">Professionelle løsninger til en grønnere fremtid</p><div className="mt-4 h-1 w-12 rounded-full bg-emerald-500" /></div></aside><main className="min-w-0 flex-1 px-4 py-5 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1280px]">
    <section className="relative overflow-hidden rounded-xl border border-slate-200 bg-white px-6 py-7 shadow-sm sm:px-8"><div className="relative z-10 max-w-2xl"><h1 className="text-3xl font-bold text-slate-900 sm:text-4xl">Min Academy</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-600">Academy træningsmiljø. Du arbejder med træningsdata. Ingen rigtige kunder, mails eller salgsdata påvirkes.</p></div><img src="/messe/machines/rc-1000s-tile.png" alt="" className="pointer-events-none absolute right-3 top-1/2 hidden h-[135%] w-80 -translate-y-1/2 object-contain opacity-90 xl:block" /></section>
    {params.get('locked') && <div className="mt-5 flex items-center gap-2 rounded-lg border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-900"><LockKeyhole className="h-4 w-4" />Denne funktion kræver Academy. Gennemfør det relevante forløb først.</div>}
    <div className="mt-5 grid gap-4 lg:grid-cols-3"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-sm font-bold text-slate-900"><BarChart3 className="h-4 w-4 text-[#126a45]" />Din progression</div><div className="mt-5 text-3xl font-bold text-slate-900">{progress.completedCount} / {progress.total}</div><ProgressBar value={progress.percentage} /><p className="mt-3 text-xs font-medium text-slate-500">{progress.percentage}% gennemført</p></section><section className="rounded-xl border border-amber-300 bg-amber-50/70 p-5 shadow-sm"><div className="flex items-center gap-2 text-sm font-bold text-slate-900"><Lock className="h-4 w-4 text-amber-700" />Næste oplåsning: Konfigurator</div><p className="mt-4 min-h-10 text-sm leading-5 text-slate-700">{unlocked ? 'Konfigurator er nu låst op.' : 'Gennemfør Sales Case 1 for at få adgang til den rigtige konfigurator.'}</p><ProgressBar value={configurator.total ? configurator.completedCount / configurator.total * 100 : 0} gold /><p className="mt-3 text-xs font-bold text-slate-700">{configurator.completedCount} / {configurator.total} gennemført</p></section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-sm font-bold text-slate-900"><Trophy className="h-4 w-4 text-amber-600" />Næste milepæl</div><p className="mt-5 text-lg font-bold text-slate-900">Bronze</p><p className="mt-1 text-sm text-slate-600">Gennemfør grundlæggende Sales-opgaver.</p><ProgressBar value={progress.percentage} /><p className="mt-3 text-xs font-bold text-slate-600">{progress.completedCount} / {progress.total}</p></section></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-3"><section className="relative overflow-hidden rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="relative z-10"><div className="flex items-center gap-2 text-sm font-bold text-slate-900"><CirclePlay className="h-4 w-4 text-[#126a45]" />Fortsæt hvor jeg slap</div><p className="mt-4 text-sm font-bold text-slate-900">Case 1 - Byg korrekt RC-1000 ordre</p><p className="mt-1 text-xs text-slate-500">{requirements} af 10 krav opfyldt</p><button type="button" onClick={startCase} className="mt-4 inline-flex items-center gap-2 rounded-md bg-[#126a45] px-3.5 py-2 text-xs font-bold text-white shadow-sm hover:bg-[#0f5a3b]">{task.started ? 'Fortsæt' : 'Start'}<ArrowRight className="h-3.5 w-3.5" /></button></div><img src="/messe/machines/rc-1000s-tile.png" alt="" className="pointer-events-none absolute -bottom-5 right-0 h-36 w-36 object-contain" /></section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-sm font-bold text-slate-900"><Medal className="h-4 w-4 text-[#126a45]" />Badges</div><div className="mt-4 space-y-3 text-xs"><div className="flex items-center gap-3"><Medal className="h-7 w-7 text-[#b77939]" /><span><b className="block text-slate-800">Bronze</b><span className="text-slate-500">Grundlæggende portalflows</span></span></div><div className="flex items-center gap-3"><ShieldCheck className="h-7 w-7 text-slate-400" /><span><b className="block text-slate-800">Sølv</b><span className="text-slate-500">Videregående Sales-flows</span></span></div><div className="flex items-center gap-3"><Crown className="h-7 w-7 text-amber-500" /><span><b className="block text-slate-800">Guld</b><span className="text-slate-500">Komplet end-to-end workflow</span></span></div></div></section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-sm font-bold text-slate-900"><Map className="h-4 w-4 text-[#126a45]" />Din Sales Academy-rejse</div><div className="mt-7 flex items-start justify-between"><Journey icon={ShoppingCart} label="Konfigurator" active={unlocked} /><Journey icon={Users} label="CRM" /><Journey icon={CirclePlay} label="Demo" /><Journey icon={Gem} label="Tilbud & ordre" /></div></section></div>
    <div className="mt-5 space-y-4"><Module icon={ShoppingCart} title="Salg" progress={`${task.completed ? 1 : 0} / 2 gennemført`}><AcademyRow image="/messe/machines/rc-1000s-tile.png" title="Case 1 - Byg korrekt RC-1000 ordre" description="Konfigurer RC-1000 med nødvendigt udstyr, rabatter og Academy-lead." state={caseState} action={task.started ? 'Fortsæt' : 'Start'} onClick={startCase} /><AcademyRow image="/messe/machines/timan-3330-tile.png" title="Case 2 - Find en vedligeholdelsesvideo" description="Find og åbn den korrekte Weed Brush-vedligeholdelsesvideo for Timan 3330." state="ready" /></Module><Module icon={Users} title="Partnerdata" progress="0 / 2 gennemført"><AcademyRow title="Part 1 - Virksomheds- og persondata" description="Tilføj rigtige kontaktpersoner, vælg første kontakt og opdater virksomhedens YouTube-kanal." state="new" /><AcademyRow title="Part 2 - Samarbejdspartnere og fakturering" description="Lær partnerrelationer og fakturaaccept for reservedelsbestilling at kende." state="locked" /></Module><Module icon={Users} title="CRM" progress="0 / 2 gennemført"><AcademyRow title="CRM Leads - grundforløb" description="Kommer senere." state="locked" /></Module><Module icon={CalendarDays} title="Kalender" progress="0 / 1 gennemført"><AcademyRow title="Kalender - grundforløb" description="Kommer senere." state="locked" /></Module></div><Link className="mt-6 inline-flex items-center gap-2 text-xs font-semibold text-[#126a45] hover:underline" to="/portal">← Tilbage til portalen</Link></div></main></div></div>;
}
