import type { PortalUiLanguage } from '@/lib/portalLanguages';

export const ACCOUNT_ORDER_DISCOUNT_TRANSLATIONS: Record<PortalUiLanguage, Record<string, string>> = {
  da: { accountOrderBaseDiscount: 'Grundrabat', accountOrderQuantityDiscount: 'Stk. rabat', accountOrderDeliveryDiscount: 'Leveringsrabat over 3 mdr.', accountOrderCampaignDiscount: 'Kampagnerabat', accountOrderDealerDiscount: 'Ekstra forhandlerrabat', accountOrderDemoDiscount: 'Demorabat', accountOrderTotalDiscount: 'Samlet rabat', accountOrderDiscount: 'Rabat' },
  en: { accountOrderBaseDiscount: 'Base discount', accountOrderQuantityDiscount: 'Quantity discount', accountOrderDeliveryDiscount: 'Delivery discount over 3 months', accountOrderCampaignDiscount: 'Campaign discount', accountOrderDealerDiscount: 'Extra dealer discount', accountOrderDemoDiscount: 'Demo discount', accountOrderTotalDiscount: 'Total discount', accountOrderDiscount: 'Discount' },
  de: { accountOrderBaseDiscount: 'Grundrabatt', accountOrderQuantityDiscount: 'Mengenrabatt', accountOrderDeliveryDiscount: 'Lieferrabatt über 3 Monate', accountOrderCampaignDiscount: 'Kampagnenrabatt', accountOrderDealerDiscount: 'Zusätzlicher Händlerrabatt', accountOrderDemoDiscount: 'Vorführrabatt', accountOrderTotalDiscount: 'Gesamtrabatt', accountOrderDiscount: 'Rabatt' },
  it: { accountOrderBaseDiscount: 'Sconto base', accountOrderQuantityDiscount: 'Sconto quantità', accountOrderDeliveryDiscount: 'Sconto consegna oltre 3 mesi', accountOrderCampaignDiscount: 'Sconto promozionale', accountOrderDealerDiscount: 'Sconto rivenditore extra', accountOrderDemoDiscount: 'Sconto dimostrazione', accountOrderTotalDiscount: 'Sconto totale', accountOrderDiscount: 'Sconto' },
  hu: { accountOrderBaseDiscount: 'Alapkedvezmény', accountOrderQuantityDiscount: 'Mennyiségi kedvezmény', accountOrderDeliveryDiscount: 'Szállítási kedvezmény 3 hónapon túl', accountOrderCampaignDiscount: 'Kampánykedvezmény', accountOrderDealerDiscount: 'Extra kereskedői kedvezmény', accountOrderDemoDiscount: 'Bemutatógép-kedvezmény', accountOrderTotalDiscount: 'Teljes kedvezmény', accountOrderDiscount: 'Kedvezmény' },
  sv: { accountOrderBaseDiscount: 'Grundrabatt', accountOrderQuantityDiscount: 'Mängdrabatt', accountOrderDeliveryDiscount: 'Leveransrabatt över 3 månader', accountOrderCampaignDiscount: 'Kampanjrabatt', accountOrderDealerDiscount: 'Extra återförsäljarrabatt', accountOrderDemoDiscount: 'Demorabatt', accountOrderTotalDiscount: 'Total rabatt', accountOrderDiscount: 'Rabatt' },
  fr: { accountOrderBaseDiscount: 'Remise de base', accountOrderQuantityDiscount: 'Remise sur quantité', accountOrderDeliveryDiscount: 'Remise livraison à plus de 3 mois', accountOrderCampaignDiscount: 'Remise promotionnelle', accountOrderDealerDiscount: 'Remise revendeur supplémentaire', accountOrderDemoDiscount: 'Remise démonstration', accountOrderTotalDiscount: 'Remise totale', accountOrderDiscount: 'Remise' },
  pl: { accountOrderBaseDiscount: 'Rabat podstawowy', accountOrderQuantityDiscount: 'Rabat ilościowy', accountOrderDeliveryDiscount: 'Rabat za dostawę powyżej 3 miesięcy', accountOrderCampaignDiscount: 'Rabat promocyjny', accountOrderDealerDiscount: 'Dodatkowy rabat dealerski', accountOrderDemoDiscount: 'Rabat demonstracyjny', accountOrderTotalDiscount: 'Łączny rabat', accountOrderDiscount: 'Rabat' },
  cs: { accountOrderBaseDiscount: 'Základní sleva', accountOrderQuantityDiscount: 'Množstevní sleva', accountOrderDeliveryDiscount: 'Sleva za dodání po více než 3 měsících', accountOrderCampaignDiscount: 'Akční sleva', accountOrderDealerDiscount: 'Dodatečná dealerská sleva', accountOrderDemoDiscount: 'Sleva na předváděcí stroj', accountOrderTotalDiscount: 'Celková sleva', accountOrderDiscount: 'Sleva' },
};
