import type { PortalUiLanguage } from '@/lib/portalLanguages';

type Dict = Record<string, string>;

const da: Dict = {
  crmDealerDashDashboard: 'Dashboard', crmDealerDashPartnerList: 'Partnerliste', crmDealerDashQuickSelect: 'Hurtigvalg',
  crmDealerDashToday: 'I dag', crmDealerDashThisMonth: 'Denne måned', crmDealerDashThisQuarter: 'Dette kvartal', crmDealerDashThisYear: 'Dette år', crmDealerDashLastYear: 'Sidste år', crmDealerDashAll: 'Alle',
  crmDealerDashReset: 'Nulstil', crmDealerDashExport: 'Eksporter', crmDealerDashPeriod: 'Periode', crmDealerDashDateFrom: 'Dato fra', crmDealerDashDateTo: 'Dato til', crmDealerDashYearFrom: 'År fra', crmDealerDashYearTo: 'År til', crmDealerDashAllYears: 'Alle år',
  crmDealerDashCountry: 'Land', crmDealerDashSeller: 'Sælger', crmDealerDashDealer: 'Forhandler', crmDealerDashCustomer: 'Kunde', crmDealerDashMachineModel: 'Maskine / model', crmDealerDashPartnerType: 'Partnertype', crmDealerDashImporter: 'Importør', crmDealerDashServicePartner: 'Servicepartner',
  crmDealerDashSelected: '{count} valgt', crmDealerDashSearch: 'Søg {label}...', crmDealerDashCurrency: 'Valuta', crmDealerDashBoth: 'Begge', crmDealerDashMoreFilters: 'Flere filtre', crmDealerDashDatePriority: 'Dato har prioritet', crmDealerDashCanonicalRows: '{count} canonical rækker',
  crmDealerDashTotalRevenue: 'Omsætning total', crmDealerDashOrderCount: 'Antal ordrer', crmDealerDashMachinesSold: 'Solgte maskiner', crmDealerDashAverageDiscount: 'Gns. rabat', crmDealerDashExtraDiscountTotal: 'Ekstra rabat i alt', crmDealerDashPaymentDeliveryDiscount: 'Betalings-/leveringsrabat', crmDealerDashTopCountry: 'Top land', crmDealerDashTopDealer: 'Top forhandler',
  crmDealerDashSubmittedOrders: 'Afgivne ordrer', crmDealerDashMachinesTotal: 'Maskiner i alt', crmDealerDashTotalDiscount: 'Samlet rabat', crmDealerDashNormalizedDkk: 'DKK-normaliseret for samlet visning', crmDealerDashShownIn: 'Vises i {currency}', crmDealerDashUnavailable: 'Ikke tilgængeligt', crmDealerDashMissingRows: '{count} ordrer mangler canonical rabatdetaljer', crmDealerDashNoData: 'Ingen data',
  crmDealerDashRevenueOverTime: 'Omsætning over tid', crmDealerDashRevenueByYear: 'Omsætning pr. kalenderår', crmDealerDashTopTenDealers: 'Top 10 forhandlere', crmDealerDashRevenueByCountry: 'Omsætning pr. land', crmDealerDashRevenueBySeller: 'Omsætning pr. sælger', crmDealerDashMachineSalesUnits: 'Salg af maskiner (stk.)', crmDealerDashMachineSalesValue: 'Maskinsalg i værdi', crmDealerDashDkVsDeRevenue: 'DK vs DE - omsætning', crmDealerDashDiscountByMachine: 'Rabatfordeling pr. maskine', crmDealerDashAverageDiscountOverTime: 'Gns. rabat over tid', crmDealerDashDiscountValueByYear: 'Rabat i værdi pr. år',
  crmDealerDashClickBar: 'Klik en søjle for at filtrere', crmDealerDashPartnerSalesContacts: 'Partnerdata: salgskontakter. Manglende kontakt vises som Info mangler.', crmDealerDashSelectedPeriod: 'Samlet i valgt periode', crmDealerDashAnnualDistribution: 'Årlig fordeling', crmDealerDashAveragePercent: 'Gennemsnit i procent', crmDealerDashEmptyChart: 'Ingen data i det valgte udsnit.',
  crmDealerDashStandard: 'Standard', crmDealerDashExtra: 'Ekstra', crmDealerDashPaymentDelivery: 'Betaling/levering', crmDealerDashCombined: 'Samlet', crmDealerDashRevenue: 'Omsætning', crmDealerDashMachines: 'Maskiner',
  crmDealerDashDetails: 'Ordre- og rabatdetaljer', crmDealerDashDetailsNote: 'Canonical data fra indsendte ordrer og frosne pris-snapshots.', crmDealerDashRows: '{count} rækker', crmDealerDashNoMatchingRows: 'Ingen rækker matcher filtrene.',
  crmDealerDashOrderNo: 'Ordrenr.', crmDealerDashQuoteNo: 'Tilbudsnr.', crmDealerDashDate: 'Dato', crmDealerDashMachine: 'Maskine', crmDealerDashListPrice: 'Listepris', crmDealerDashExtraAmount: 'Ekstra beløb', crmDealerDashPaymentDeliveryAmount: 'Betaling/levering beløb', crmDealerDashDiscountTotal: 'Rabat i alt', crmDealerDashNet: 'Netto', crmDealerDashGrossMargin: 'DB',
  crmDealerDashLoadError: 'Dashboard-data kunne ikke indlæses: {error}', crmDealerDashLoading: 'Indlæser dashboard-data…', crmDealerDashLocalScope: 'Lokal scope-simulering', crmDealerDashScopeNote: 'Filtermulighederne bygges fra scopet og kan derfor kun indsnævre data.', crmDealerDashLocalRows: 'Lokal prototype · {count} scoped rækker',
};

const en: Dict = {
  crmDealerDashDashboard: 'Dashboard', crmDealerDashPartnerList: 'Partner list', crmDealerDashQuickSelect: 'Quick select',
  crmDealerDashToday: 'Today', crmDealerDashThisMonth: 'This month', crmDealerDashThisQuarter: 'This quarter', crmDealerDashThisYear: 'This year', crmDealerDashLastYear: 'Last year', crmDealerDashAll: 'All',
  crmDealerDashReset: 'Reset', crmDealerDashExport: 'Export', crmDealerDashPeriod: 'Period', crmDealerDashDateFrom: 'Date from', crmDealerDashDateTo: 'Date to', crmDealerDashYearFrom: 'Year from', crmDealerDashYearTo: 'Year to', crmDealerDashAllYears: 'All years',
  crmDealerDashCountry: 'Country', crmDealerDashSeller: 'Seller', crmDealerDashDealer: 'Dealer', crmDealerDashCustomer: 'Customer', crmDealerDashMachineModel: 'Machine / model', crmDealerDashPartnerType: 'Partner type', crmDealerDashImporter: 'Importer', crmDealerDashServicePartner: 'Service partner',
  crmDealerDashSelected: '{count} selected', crmDealerDashSearch: 'Search {label}...', crmDealerDashCurrency: 'Currency', crmDealerDashBoth: 'Both', crmDealerDashMoreFilters: 'More filters', crmDealerDashDatePriority: 'Date takes priority', crmDealerDashCanonicalRows: '{count} canonical rows',
  crmDealerDashTotalRevenue: 'Total revenue', crmDealerDashOrderCount: 'Number of orders', crmDealerDashMachinesSold: 'Machines sold', crmDealerDashAverageDiscount: 'Avg. discount', crmDealerDashExtraDiscountTotal: 'Total extra discount', crmDealerDashPaymentDeliveryDiscount: 'Payment/delivery discount', crmDealerDashTopCountry: 'Top country', crmDealerDashTopDealer: 'Top dealer',
  crmDealerDashSubmittedOrders: 'Submitted orders', crmDealerDashMachinesTotal: 'Machines in total', crmDealerDashTotalDiscount: 'Total discount', crmDealerDashNormalizedDkk: 'DKK-normalized for combined view', crmDealerDashShownIn: 'Shown in {currency}', crmDealerDashUnavailable: 'Not available', crmDealerDashMissingRows: '{count} orders lack canonical discount details', crmDealerDashNoData: 'No data',
  crmDealerDashRevenueOverTime: 'Revenue over time', crmDealerDashRevenueByYear: 'Revenue by calendar year', crmDealerDashTopTenDealers: 'Top 10 dealers', crmDealerDashRevenueByCountry: 'Revenue by country', crmDealerDashRevenueBySeller: 'Revenue by seller', crmDealerDashMachineSalesUnits: 'Machine sales (units)', crmDealerDashMachineSalesValue: 'Machine sales value', crmDealerDashDkVsDeRevenue: 'DK vs DE - revenue', crmDealerDashDiscountByMachine: 'Discount distribution by machine', crmDealerDashAverageDiscountOverTime: 'Avg. discount over time', crmDealerDashDiscountValueByYear: 'Discount value by year',
  crmDealerDashClickBar: 'Click a bar to filter', crmDealerDashPartnerSalesContacts: 'Partner data: sales contacts. A missing contact is shown as Missing info.', crmDealerDashSelectedPeriod: 'Total in selected period', crmDealerDashAnnualDistribution: 'Annual distribution', crmDealerDashAveragePercent: 'Average percentage', crmDealerDashEmptyChart: 'No data in the selected range.',
  crmDealerDashStandard: 'Standard', crmDealerDashExtra: 'Extra', crmDealerDashPaymentDelivery: 'Payment/delivery', crmDealerDashCombined: 'Total', crmDealerDashRevenue: 'Revenue', crmDealerDashMachines: 'Machines',
  crmDealerDashDetails: 'Order and discount details', crmDealerDashDetailsNote: 'Canonical data from submitted orders and frozen pricing snapshots.', crmDealerDashRows: '{count} rows', crmDealerDashNoMatchingRows: 'No rows match the filters.',
  crmDealerDashOrderNo: 'Order no.', crmDealerDashQuoteNo: 'Quote no.', crmDealerDashDate: 'Date', crmDealerDashMachine: 'Machine', crmDealerDashListPrice: 'List price', crmDealerDashExtraAmount: 'Extra amount', crmDealerDashPaymentDeliveryAmount: 'Payment/delivery amount', crmDealerDashDiscountTotal: 'Total discount', crmDealerDashNet: 'Net', crmDealerDashGrossMargin: 'GM',
  crmDealerDashLoadError: 'Dashboard data could not be loaded: {error}', crmDealerDashLoading: 'Loading dashboard data…', crmDealerDashLocalScope: 'Local scope simulation', crmDealerDashScopeNote: 'Filters are built from the scope and can therefore only narrow the data.', crmDealerDashLocalRows: 'Local prototype · {count} scoped rows',
};

const de: Dict = {
  crmDealerDashDashboard: 'Dashboard', crmDealerDashPartnerList: 'Partnerliste', crmDealerDashQuickSelect: 'Schnellauswahl',
  crmDealerDashToday: 'Heute', crmDealerDashThisMonth: 'Dieser Monat', crmDealerDashThisQuarter: 'Dieses Quartal', crmDealerDashThisYear: 'Dieses Jahr', crmDealerDashLastYear: 'Letztes Jahr', crmDealerDashAll: 'Alle',
  crmDealerDashReset: 'Zurücksetzen', crmDealerDashExport: 'Exportieren', crmDealerDashPeriod: 'Zeitraum', crmDealerDashDateFrom: 'Datum von', crmDealerDashDateTo: 'Datum bis', crmDealerDashYearFrom: 'Jahr von', crmDealerDashYearTo: 'Jahr bis', crmDealerDashAllYears: 'Alle Jahre',
  crmDealerDashCountry: 'Land', crmDealerDashSeller: 'Verkäufer', crmDealerDashDealer: 'Händler', crmDealerDashCustomer: 'Kunde', crmDealerDashMachineModel: 'Maschine / Modell', crmDealerDashPartnerType: 'Partnertyp', crmDealerDashImporter: 'Importeur', crmDealerDashServicePartner: 'Servicepartner',
  crmDealerDashSelected: '{count} ausgewählt', crmDealerDashSearch: '{label} suchen...', crmDealerDashCurrency: 'Währung', crmDealerDashBoth: 'Beide', crmDealerDashMoreFilters: 'Weitere Filter', crmDealerDashDatePriority: 'Datum hat Vorrang', crmDealerDashCanonicalRows: '{count} kanonische Zeilen',
  crmDealerDashTotalRevenue: 'Gesamtumsatz', crmDealerDashOrderCount: 'Anzahl Bestellungen', crmDealerDashMachinesSold: 'Verkaufte Maschinen', crmDealerDashAverageDiscount: 'Durchschn. Rabatt', crmDealerDashExtraDiscountTotal: 'Zusatzrabatt gesamt', crmDealerDashPaymentDeliveryDiscount: 'Zahlungs-/Lieferungsrabatt', crmDealerDashTopCountry: 'Top-Land', crmDealerDashTopDealer: 'Top-Händler',
  crmDealerDashSubmittedOrders: 'Erteilte Bestellungen', crmDealerDashMachinesTotal: 'Maschinen insgesamt', crmDealerDashTotalDiscount: 'Gesamtrabatt', crmDealerDashNormalizedDkk: 'Für Gesamtansicht in DKK normalisiert', crmDealerDashShownIn: 'Anzeige in {currency}', crmDealerDashUnavailable: 'Nicht verfügbar', crmDealerDashMissingRows: '{count} Bestellungen ohne kanonische Rabattdetails', crmDealerDashNoData: 'Keine Daten',
  crmDealerDashRevenueOverTime: 'Umsatz im Zeitverlauf', crmDealerDashRevenueByYear: 'Umsatz pro Kalenderjahr', crmDealerDashTopTenDealers: 'Top 10 Händler', crmDealerDashRevenueByCountry: 'Umsatz nach Land', crmDealerDashRevenueBySeller: 'Umsatz nach Verkäufer', crmDealerDashMachineSalesUnits: 'Maschinenverkäufe (Stk.)', crmDealerDashMachineSalesValue: 'Maschinenverkaufswert', crmDealerDashDkVsDeRevenue: 'DK vs. DE - Umsatz', crmDealerDashDiscountByMachine: 'Rabattverteilung pro Maschine', crmDealerDashAverageDiscountOverTime: 'Durchschn. Rabatt im Zeitverlauf', crmDealerDashDiscountValueByYear: 'Rabattwert pro Jahr',
  crmDealerDashClickBar: 'Zum Filtern auf einen Balken klicken', crmDealerDashPartnerSalesContacts: 'Partnerdaten: Verkaufskontakte. Fehlende Kontakte werden als Fehlende Info angezeigt.', crmDealerDashSelectedPeriod: 'Gesamt im gewählten Zeitraum', crmDealerDashAnnualDistribution: 'Jährliche Verteilung', crmDealerDashAveragePercent: 'Durchschnitt in Prozent', crmDealerDashEmptyChart: 'Keine Daten im gewählten Ausschnitt.',
  crmDealerDashStandard: 'Standard', crmDealerDashExtra: 'Zusatz', crmDealerDashPaymentDelivery: 'Zahlung/Lieferung', crmDealerDashCombined: 'Gesamt', crmDealerDashRevenue: 'Umsatz', crmDealerDashMachines: 'Maschinen',
  crmDealerDashDetails: 'Bestell- und Rabattdetails', crmDealerDashDetailsNote: 'Kanonische Daten aus erteilten Bestellungen und eingefrorenen Preis-Snapshots.', crmDealerDashRows: '{count} Zeilen', crmDealerDashNoMatchingRows: 'Keine Zeilen entsprechen den Filtern.',
  crmDealerDashOrderNo: 'Bestellnr.', crmDealerDashQuoteNo: 'Angebotsnr.', crmDealerDashDate: 'Datum', crmDealerDashMachine: 'Maschine', crmDealerDashListPrice: 'Listenpreis', crmDealerDashExtraAmount: 'Zusatzbetrag', crmDealerDashPaymentDeliveryAmount: 'Zahlung/Lieferung Betrag', crmDealerDashDiscountTotal: 'Rabatt gesamt', crmDealerDashNet: 'Netto', crmDealerDashGrossMargin: 'DB',
  crmDealerDashLoadError: 'Dashboard-Daten konnten nicht geladen werden: {error}', crmDealerDashLoading: 'Dashboard-Daten werden geladen…', crmDealerDashLocalScope: 'Lokale Scope-Simulation', crmDealerDashScopeNote: 'Filter werden aus dem Scope aufgebaut und können die Daten daher nur eingrenzen.', crmDealerDashLocalRows: 'Lokaler Prototyp · {count} Scope-Zeilen',
};

const it: Dict = {
  ...en,
  crmDealerDashPartnerList: 'Elenco partner', crmDealerDashQuickSelect: 'Selezione rapida', crmDealerDashToday: 'Oggi', crmDealerDashThisMonth: 'Questo mese', crmDealerDashThisQuarter: 'Questo trimestre', crmDealerDashThisYear: 'Quest’anno', crmDealerDashLastYear: 'Anno scorso', crmDealerDashAll: 'Tutti', crmDealerDashReset: 'Reimposta', crmDealerDashExport: 'Esporta', crmDealerDashPeriod: 'Periodo', crmDealerDashDateFrom: 'Data da', crmDealerDashDateTo: 'Data a', crmDealerDashYearFrom: 'Anno da', crmDealerDashYearTo: 'Anno a', crmDealerDashAllYears: 'Tutti gli anni',
  crmDealerDashCountry: 'Paese', crmDealerDashSeller: 'Venditore', crmDealerDashDealer: 'Rivenditore', crmDealerDashCustomer: 'Cliente', crmDealerDashMachineModel: 'Macchina / modello', crmDealerDashPartnerType: 'Tipo di partner', crmDealerDashImporter: 'Importatore', crmDealerDashServicePartner: 'Partner assistenza', crmDealerDashSelected: '{count} selezionati', crmDealerDashSearch: 'Cerca {label}...', crmDealerDashCurrency: 'Valuta', crmDealerDashBoth: 'Entrambe', crmDealerDashMoreFilters: 'Altri filtri', crmDealerDashDatePriority: 'La data ha priorità', crmDealerDashCanonicalRows: '{count} righe canoniche',
  crmDealerDashTotalRevenue: 'Fatturato totale', crmDealerDashOrderCount: 'Numero di ordini', crmDealerDashMachinesSold: 'Macchine vendute', crmDealerDashAverageDiscount: 'Sconto medio', crmDealerDashExtraDiscountTotal: 'Sconto extra totale', crmDealerDashPaymentDeliveryDiscount: 'Sconto pagamento/consegna', crmDealerDashTopCountry: 'Paese principale', crmDealerDashTopDealer: 'Rivenditore principale', crmDealerDashSubmittedOrders: 'Ordini inviati', crmDealerDashMachinesTotal: 'Macchine totali', crmDealerDashTotalDiscount: 'Sconto totale', crmDealerDashNormalizedDkk: 'Normalizzato in DKK per la vista combinata', crmDealerDashShownIn: 'Visualizzato in {currency}', crmDealerDashUnavailable: 'Non disponibile', crmDealerDashMissingRows: '{count} ordini senza dettagli sconto canonici', crmDealerDashNoData: 'Nessun dato',
  crmDealerDashRevenueOverTime: 'Fatturato nel tempo', crmDealerDashRevenueByYear: 'Fatturato per anno solare', crmDealerDashTopTenDealers: 'Top 10 rivenditori', crmDealerDashRevenueByCountry: 'Fatturato per paese', crmDealerDashRevenueBySeller: 'Fatturato per venditore', crmDealerDashMachineSalesUnits: 'Vendite macchine (unità)', crmDealerDashMachineSalesValue: 'Valore vendite macchine', crmDealerDashDkVsDeRevenue: 'DK vs DE - fatturato', crmDealerDashDiscountByMachine: 'Distribuzione sconti per macchina', crmDealerDashAverageDiscountOverTime: 'Sconto medio nel tempo', crmDealerDashDiscountValueByYear: 'Valore sconto per anno', crmDealerDashClickBar: 'Fai clic su una barra per filtrare', crmDealerDashSelectedPeriod: 'Totale nel periodo selezionato', crmDealerDashAnnualDistribution: 'Distribuzione annuale', crmDealerDashAveragePercent: 'Media percentuale', crmDealerDashEmptyChart: 'Nessun dato nell’intervallo selezionato.',
  crmDealerDashStandard: 'Standard', crmDealerDashExtra: 'Extra', crmDealerDashPaymentDelivery: 'Pagamento/consegna', crmDealerDashCombined: 'Totale', crmDealerDashRevenue: 'Fatturato', crmDealerDashMachines: 'Macchine', crmDealerDashDetails: 'Dettagli ordini e sconti', crmDealerDashDetailsNote: 'Dati canonici da ordini inviati e snapshot dei prezzi bloccati.', crmDealerDashRows: '{count} righe', crmDealerDashNoMatchingRows: 'Nessuna riga corrisponde ai filtri.', crmDealerDashOrderNo: 'N. ordine', crmDealerDashQuoteNo: 'N. offerta', crmDealerDashDate: 'Data', crmDealerDashMachine: 'Macchina', crmDealerDashListPrice: 'Prezzo di listino', crmDealerDashExtraAmount: 'Importo extra', crmDealerDashPaymentDeliveryAmount: 'Importo pagamento/consegna', crmDealerDashDiscountTotal: 'Sconto totale', crmDealerDashNet: 'Netto', crmDealerDashLoadError: 'Impossibile caricare i dati del dashboard: {error}', crmDealerDashLoading: 'Caricamento dati dashboard…',
  crmDealerDashPartnerSalesContacts: 'Dati partner: contatti vendita. Un contatto mancante viene indicato come Informazioni mancanti.', crmDealerDashGrossMargin: 'Margine', crmDealerDashLocalScope: 'Simulazione ambito locale', crmDealerDashScopeNote: 'I filtri partono dall’ambito e possono quindi solo restringere i dati.', crmDealerDashLocalRows: 'Prototipo locale · {count} righe nell’ambito',
};

const hu: Dict = {
  ...en,
  crmDealerDashPartnerList: 'Partnerlista', crmDealerDashQuickSelect: 'Gyorsválasztás', crmDealerDashToday: 'Ma', crmDealerDashThisMonth: 'Ez a hónap', crmDealerDashThisQuarter: 'Ez a negyedév', crmDealerDashThisYear: 'Ez az év', crmDealerDashLastYear: 'Tavaly', crmDealerDashAll: 'Mind', crmDealerDashReset: 'Alaphelyzet', crmDealerDashExport: 'Exportálás', crmDealerDashPeriod: 'Időszak', crmDealerDashDateFrom: 'Kezdő dátum', crmDealerDashDateTo: 'Záró dátum', crmDealerDashYearFrom: 'Kezdő év', crmDealerDashYearTo: 'Záró év', crmDealerDashAllYears: 'Minden év',
  crmDealerDashCountry: 'Ország', crmDealerDashSeller: 'Értékesítő', crmDealerDashDealer: 'Kereskedő', crmDealerDashCustomer: 'Ügyfél', crmDealerDashMachineModel: 'Gép / modell', crmDealerDashPartnerType: 'Partnertípus', crmDealerDashImporter: 'Importőr', crmDealerDashServicePartner: 'Szervizpartner', crmDealerDashSelected: '{count} kiválasztva', crmDealerDashSearch: '{label} keresése...', crmDealerDashCurrency: 'Pénznem', crmDealerDashBoth: 'Mindkettő', crmDealerDashMoreFilters: 'További szűrők', crmDealerDashDatePriority: 'A dátum elsőbbséget élvez', crmDealerDashCanonicalRows: '{count} kanonikus sor',
  crmDealerDashTotalRevenue: 'Teljes árbevétel', crmDealerDashOrderCount: 'Rendelések száma', crmDealerDashMachinesSold: 'Eladott gépek', crmDealerDashAverageDiscount: 'Átlagos kedvezmény', crmDealerDashExtraDiscountTotal: 'Összes extra kedvezmény', crmDealerDashPaymentDeliveryDiscount: 'Fizetési/szállítási kedvezmény', crmDealerDashTopCountry: 'Legjobb ország', crmDealerDashTopDealer: 'Legjobb kereskedő', crmDealerDashSubmittedOrders: 'Leadott rendelések', crmDealerDashMachinesTotal: 'Gépek összesen', crmDealerDashTotalDiscount: 'Teljes kedvezmény', crmDealerDashNormalizedDkk: 'DKK-ra normalizálva az összesített nézethez', crmDealerDashShownIn: 'Megjelenítés: {currency}', crmDealerDashUnavailable: 'Nem érhető el', crmDealerDashMissingRows: '{count} rendelésből hiányoznak a kanonikus kedvezményrészletek', crmDealerDashNoData: 'Nincs adat',
  crmDealerDashRevenueOverTime: 'Árbevétel időben', crmDealerDashRevenueByYear: 'Árbevétel naptári évenként', crmDealerDashTopTenDealers: 'Top 10 kereskedő', crmDealerDashRevenueByCountry: 'Árbevétel országonként', crmDealerDashRevenueBySeller: 'Árbevétel értékesítőnként', crmDealerDashMachineSalesUnits: 'Gépértékesítés (db)', crmDealerDashMachineSalesValue: 'Gépértékesítés értéke', crmDealerDashDkVsDeRevenue: 'DK vs DE - árbevétel', crmDealerDashDiscountByMachine: 'Kedvezményeloszlás gépenként', crmDealerDashAverageDiscountOverTime: 'Átlagos kedvezmény időben', crmDealerDashDiscountValueByYear: 'Kedvezményérték évenként', crmDealerDashClickBar: 'Szűréshez kattintson egy oszlopra', crmDealerDashSelectedPeriod: 'Összesen a kiválasztott időszakban', crmDealerDashAnnualDistribution: 'Éves eloszlás', crmDealerDashAveragePercent: 'Átlag százalékban', crmDealerDashEmptyChart: 'Nincs adat a kiválasztott tartományban.',
  crmDealerDashStandard: 'Alap', crmDealerDashExtra: 'Extra', crmDealerDashPaymentDelivery: 'Fizetés/szállítás', crmDealerDashCombined: 'Összesen', crmDealerDashRevenue: 'Árbevétel', crmDealerDashMachines: 'Gépek', crmDealerDashDetails: 'Rendelés- és kedvezményrészletek', crmDealerDashDetailsNote: 'Kanonikus adatok leadott rendelésekből és rögzített árpillanatképekből.', crmDealerDashRows: '{count} sor', crmDealerDashNoMatchingRows: 'Egyetlen sor sem felel meg a szűrőknek.', crmDealerDashOrderNo: 'Rendelésszám', crmDealerDashQuoteNo: 'Ajánlatszám', crmDealerDashDate: 'Dátum', crmDealerDashMachine: 'Gép', crmDealerDashListPrice: 'Listaár', crmDealerDashExtraAmount: 'Extra összeg', crmDealerDashPaymentDeliveryAmount: 'Fizetési/szállítási összeg', crmDealerDashDiscountTotal: 'Kedvezmény összesen', crmDealerDashNet: 'Nettó', crmDealerDashLoadError: 'A dashboard adatai nem tölthetők be: {error}', crmDealerDashLoading: 'Dashboard-adatok betöltése…',
  crmDealerDashPartnerSalesContacts: 'Partneradatok: értékesítési kapcsolatok. A hiányzó kapcsolat Hiányzó információként jelenik meg.', crmDealerDashGrossMargin: 'Árrés', crmDealerDashLocalScope: 'Helyi hatókör-szimuláció', crmDealerDashScopeNote: 'A szűrők a hatókörből épülnek fel, ezért csak szűkíthetik az adatokat.', crmDealerDashLocalRows: 'Helyi prototípus · {count} hatókörbe tartozó sor',
};

const sv: Dict = {
  ...en,
  crmDealerDashPartnerList: 'Partnerlista', crmDealerDashQuickSelect: 'Snabbval', crmDealerDashToday: 'I dag', crmDealerDashThisMonth: 'Denna månad', crmDealerDashThisQuarter: 'Detta kvartal', crmDealerDashThisYear: 'Detta år', crmDealerDashLastYear: 'Förra året', crmDealerDashAll: 'Alla', crmDealerDashReset: 'Återställ', crmDealerDashExport: 'Exportera', crmDealerDashPeriod: 'Period', crmDealerDashDateFrom: 'Datum från', crmDealerDashDateTo: 'Datum till', crmDealerDashYearFrom: 'År från', crmDealerDashYearTo: 'År till', crmDealerDashAllYears: 'Alla år',
  crmDealerDashCountry: 'Land', crmDealerDashSeller: 'Säljare', crmDealerDashDealer: 'Återförsäljare', crmDealerDashCustomer: 'Kund', crmDealerDashMachineModel: 'Maskin / modell', crmDealerDashPartnerType: 'Partnertyp', crmDealerDashImporter: 'Importör', crmDealerDashServicePartner: 'Servicepartner', crmDealerDashSelected: '{count} valda', crmDealerDashSearch: 'Sök {label}...', crmDealerDashCurrency: 'Valuta', crmDealerDashBoth: 'Båda', crmDealerDashMoreFilters: 'Fler filter', crmDealerDashDatePriority: 'Datum har prioritet', crmDealerDashCanonicalRows: '{count} kanoniska rader',
  crmDealerDashTotalRevenue: 'Total omsättning', crmDealerDashOrderCount: 'Antal ordrar', crmDealerDashMachinesSold: 'Sålda maskiner', crmDealerDashAverageDiscount: 'Genomsnittlig rabatt', crmDealerDashExtraDiscountTotal: 'Extra rabatt totalt', crmDealerDashPaymentDeliveryDiscount: 'Betalnings-/leveransrabatt', crmDealerDashTopCountry: 'Toppland', crmDealerDashTopDealer: 'Toppåterförsäljare', crmDealerDashSubmittedOrders: 'Lagda ordrar', crmDealerDashMachinesTotal: 'Maskiner totalt', crmDealerDashTotalDiscount: 'Total rabatt', crmDealerDashNormalizedDkk: 'DKK-normaliserat för samlad vy', crmDealerDashShownIn: 'Visas i {currency}', crmDealerDashUnavailable: 'Inte tillgängligt', crmDealerDashMissingRows: '{count} ordrar saknar kanoniska rabattdetaljer', crmDealerDashNoData: 'Inga data',
  crmDealerDashRevenueOverTime: 'Omsättning över tid', crmDealerDashRevenueByYear: 'Omsättning per kalenderår', crmDealerDashTopTenDealers: 'Topp 10 återförsäljare', crmDealerDashRevenueByCountry: 'Omsättning per land', crmDealerDashRevenueBySeller: 'Omsättning per säljare', crmDealerDashMachineSalesUnits: 'Maskinförsäljning (st.)', crmDealerDashMachineSalesValue: 'Maskinförsäljning i värde', crmDealerDashDkVsDeRevenue: 'DK mot DE - omsättning', crmDealerDashDiscountByMachine: 'Rabattfördelning per maskin', crmDealerDashAverageDiscountOverTime: 'Genomsnittlig rabatt över tid', crmDealerDashDiscountValueByYear: 'Rabattvärde per år', crmDealerDashClickBar: 'Klicka på en stapel för att filtrera', crmDealerDashSelectedPeriod: 'Totalt under vald period', crmDealerDashAnnualDistribution: 'Årlig fördelning', crmDealerDashAveragePercent: 'Genomsnitt i procent', crmDealerDashEmptyChart: 'Inga data i valt urval.',
  crmDealerDashStandard: 'Standard', crmDealerDashExtra: 'Extra', crmDealerDashPaymentDelivery: 'Betalning/leverans', crmDealerDashCombined: 'Totalt', crmDealerDashRevenue: 'Omsättning', crmDealerDashMachines: 'Maskiner', crmDealerDashDetails: 'Order- och rabattdetaljer', crmDealerDashDetailsNote: 'Kanoniska data från lagda ordrar och frysta prisögonblicksbilder.', crmDealerDashRows: '{count} rader', crmDealerDashNoMatchingRows: 'Inga rader matchar filtren.', crmDealerDashOrderNo: 'Ordernr.', crmDealerDashQuoteNo: 'Offertnr.', crmDealerDashDate: 'Datum', crmDealerDashMachine: 'Maskin', crmDealerDashListPrice: 'Listpris', crmDealerDashExtraAmount: 'Extra belopp', crmDealerDashPaymentDeliveryAmount: 'Betalnings-/leveransbelopp', crmDealerDashDiscountTotal: 'Rabatt totalt', crmDealerDashNet: 'Netto', crmDealerDashLoadError: 'Dashboarddata kunde inte läsas in: {error}', crmDealerDashLoading: 'Läser in dashboarddata…',
  crmDealerDashPartnerSalesContacts: 'Partnerdata: försäljningskontakter. En saknad kontakt visas som Information saknas.', crmDealerDashGrossMargin: 'TB', crmDealerDashLocalScope: 'Lokal omfattningssimulering', crmDealerDashScopeNote: 'Filtren byggs från omfattningen och kan därför bara begränsa data.', crmDealerDashLocalRows: 'Lokal prototyp · {count} rader i omfattningen',
};

const fr: Dict = {
  ...en,
  crmDealerDashPartnerList: 'Liste des partenaires', crmDealerDashQuickSelect: 'Sélection rapide', crmDealerDashToday: 'Aujourd’hui', crmDealerDashThisMonth: 'Ce mois-ci', crmDealerDashThisQuarter: 'Ce trimestre', crmDealerDashThisYear: 'Cette année', crmDealerDashLastYear: 'Année dernière', crmDealerDashAll: 'Tous', crmDealerDashReset: 'Réinitialiser', crmDealerDashExport: 'Exporter', crmDealerDashPeriod: 'Période', crmDealerDashDateFrom: 'Date de début', crmDealerDashDateTo: 'Date de fin', crmDealerDashYearFrom: 'Année de début', crmDealerDashYearTo: 'Année de fin', crmDealerDashAllYears: 'Toutes les années',
  crmDealerDashCountry: 'Pays', crmDealerDashSeller: 'Vendeur', crmDealerDashDealer: 'Revendeur', crmDealerDashCustomer: 'Client', crmDealerDashMachineModel: 'Machine / modèle', crmDealerDashPartnerType: 'Type de partenaire', crmDealerDashImporter: 'Importateur', crmDealerDashServicePartner: 'Partenaire de service', crmDealerDashSelected: '{count} sélectionnés', crmDealerDashSearch: 'Rechercher {label}...', crmDealerDashCurrency: 'Devise', crmDealerDashBoth: 'Les deux', crmDealerDashMoreFilters: 'Plus de filtres', crmDealerDashDatePriority: 'La date est prioritaire', crmDealerDashCanonicalRows: '{count} lignes canoniques',
  crmDealerDashTotalRevenue: 'Chiffre d’affaires total', crmDealerDashOrderCount: 'Nombre de commandes', crmDealerDashMachinesSold: 'Machines vendues', crmDealerDashAverageDiscount: 'Remise moyenne', crmDealerDashExtraDiscountTotal: 'Remise supplémentaire totale', crmDealerDashPaymentDeliveryDiscount: 'Remise paiement/livraison', crmDealerDashTopCountry: 'Premier pays', crmDealerDashTopDealer: 'Premier revendeur', crmDealerDashSubmittedOrders: 'Commandes passées', crmDealerDashMachinesTotal: 'Machines au total', crmDealerDashTotalDiscount: 'Remise totale', crmDealerDashNormalizedDkk: 'Normalisé en DKK pour la vue combinée', crmDealerDashShownIn: 'Affiché en {currency}', crmDealerDashUnavailable: 'Non disponible', crmDealerDashMissingRows: '{count} commandes sans détails de remise canoniques', crmDealerDashNoData: 'Aucune donnée',
  crmDealerDashRevenueOverTime: 'Chiffre d’affaires dans le temps', crmDealerDashRevenueByYear: 'Chiffre d’affaires par année civile', crmDealerDashTopTenDealers: 'Top 10 des revendeurs', crmDealerDashRevenueByCountry: 'Chiffre d’affaires par pays', crmDealerDashRevenueBySeller: 'Chiffre d’affaires par vendeur', crmDealerDashMachineSalesUnits: 'Ventes de machines (unités)', crmDealerDashMachineSalesValue: 'Valeur des ventes de machines', crmDealerDashDkVsDeRevenue: 'DK vs DE - chiffre d’affaires', crmDealerDashDiscountByMachine: 'Répartition des remises par machine', crmDealerDashAverageDiscountOverTime: 'Remise moyenne dans le temps', crmDealerDashDiscountValueByYear: 'Valeur des remises par an', crmDealerDashClickBar: 'Cliquez sur une barre pour filtrer', crmDealerDashSelectedPeriod: 'Total sur la période sélectionnée', crmDealerDashAnnualDistribution: 'Répartition annuelle', crmDealerDashAveragePercent: 'Moyenne en pourcentage', crmDealerDashEmptyChart: 'Aucune donnée dans la sélection.',
  crmDealerDashStandard: 'Standard', crmDealerDashExtra: 'Supplémentaire', crmDealerDashPaymentDelivery: 'Paiement/livraison', crmDealerDashCombined: 'Total', crmDealerDashRevenue: 'Chiffre d’affaires', crmDealerDashMachines: 'Machines', crmDealerDashDetails: 'Détails des commandes et remises', crmDealerDashDetailsNote: 'Données canoniques des commandes passées et instantanés tarifaires figés.', crmDealerDashRows: '{count} lignes', crmDealerDashNoMatchingRows: 'Aucune ligne ne correspond aux filtres.', crmDealerDashOrderNo: 'N° commande', crmDealerDashQuoteNo: 'N° offre', crmDealerDashDate: 'Date', crmDealerDashMachine: 'Machine', crmDealerDashListPrice: 'Prix catalogue', crmDealerDashExtraAmount: 'Montant supplémentaire', crmDealerDashPaymentDeliveryAmount: 'Montant paiement/livraison', crmDealerDashDiscountTotal: 'Remise totale', crmDealerDashNet: 'Net', crmDealerDashLoadError: 'Impossible de charger les données du dashboard : {error}', crmDealerDashLoading: 'Chargement des données du dashboard…',
  crmDealerDashPartnerSalesContacts: 'Données partenaire : contacts commerciaux. Un contact manquant est indiqué comme Information manquante.', crmDealerDashGrossMargin: 'Marge', crmDealerDashLocalScope: 'Simulation de périmètre local', crmDealerDashScopeNote: 'Les filtres sont construits à partir du périmètre et ne peuvent donc que réduire les données.', crmDealerDashLocalRows: 'Prototype local · {count} lignes du périmètre',
};

const pl: Dict = {
  ...en,
  crmDealerDashPartnerList: 'Lista partnerów', crmDealerDashQuickSelect: 'Szybki wybór', crmDealerDashToday: 'Dzisiaj', crmDealerDashThisMonth: 'Ten miesiąc', crmDealerDashThisQuarter: 'Ten kwartał', crmDealerDashThisYear: 'Ten rok', crmDealerDashLastYear: 'Ubiegły rok', crmDealerDashAll: 'Wszystkie', crmDealerDashReset: 'Resetuj', crmDealerDashExport: 'Eksportuj', crmDealerDashPeriod: 'Okres', crmDealerDashDateFrom: 'Data od', crmDealerDashDateTo: 'Data do', crmDealerDashYearFrom: 'Rok od', crmDealerDashYearTo: 'Rok do', crmDealerDashAllYears: 'Wszystkie lata',
  crmDealerDashCountry: 'Kraj', crmDealerDashSeller: 'Sprzedawca', crmDealerDashDealer: 'Dealer', crmDealerDashCustomer: 'Klient', crmDealerDashMachineModel: 'Maszyna / model', crmDealerDashPartnerType: 'Typ partnera', crmDealerDashImporter: 'Importer', crmDealerDashServicePartner: 'Partner serwisowy', crmDealerDashSelected: 'Wybrano: {count}', crmDealerDashSearch: 'Szukaj: {label}...', crmDealerDashCurrency: 'Waluta', crmDealerDashBoth: 'Obie', crmDealerDashMoreFilters: 'Więcej filtrów', crmDealerDashDatePriority: 'Data ma pierwszeństwo', crmDealerDashCanonicalRows: '{count} wierszy kanonicznych',
  crmDealerDashTotalRevenue: 'Łączny przychód', crmDealerDashOrderCount: 'Liczba zamówień', crmDealerDashMachinesSold: 'Sprzedane maszyny', crmDealerDashAverageDiscount: 'Średni rabat', crmDealerDashExtraDiscountTotal: 'Łączny dodatkowy rabat', crmDealerDashPaymentDeliveryDiscount: 'Rabat płatniczy/dostawczy', crmDealerDashTopCountry: 'Najlepszy kraj', crmDealerDashTopDealer: 'Najlepszy dealer', crmDealerDashSubmittedOrders: 'Złożone zamówienia', crmDealerDashMachinesTotal: 'Maszyny łącznie', crmDealerDashTotalDiscount: 'Łączny rabat', crmDealerDashNormalizedDkk: 'Znormalizowano do DKK dla widoku łącznego', crmDealerDashShownIn: 'Wyświetlane w {currency}', crmDealerDashUnavailable: 'Niedostępne', crmDealerDashMissingRows: '{count} zamówień bez kanonicznych szczegółów rabatu', crmDealerDashNoData: 'Brak danych',
  crmDealerDashRevenueOverTime: 'Przychód w czasie', crmDealerDashRevenueByYear: 'Przychód według roku kalendarzowego', crmDealerDashTopTenDealers: 'Top 10 dealerów', crmDealerDashRevenueByCountry: 'Przychód według kraju', crmDealerDashRevenueBySeller: 'Przychód według sprzedawcy', crmDealerDashMachineSalesUnits: 'Sprzedaż maszyn (szt.)', crmDealerDashMachineSalesValue: 'Wartość sprzedaży maszyn', crmDealerDashDkVsDeRevenue: 'DK vs DE - przychód', crmDealerDashDiscountByMachine: 'Rozkład rabatów według maszyny', crmDealerDashAverageDiscountOverTime: 'Średni rabat w czasie', crmDealerDashDiscountValueByYear: 'Wartość rabatu według roku', crmDealerDashClickBar: 'Kliknij słupek, aby filtrować', crmDealerDashSelectedPeriod: 'Łącznie w wybranym okresie', crmDealerDashAnnualDistribution: 'Rozkład roczny', crmDealerDashAveragePercent: 'Średnia procentowa', crmDealerDashEmptyChart: 'Brak danych w wybranym zakresie.',
  crmDealerDashStandard: 'Standardowy', crmDealerDashExtra: 'Dodatkowy', crmDealerDashPaymentDelivery: 'Płatność/dostawa', crmDealerDashCombined: 'Łącznie', crmDealerDashRevenue: 'Przychód', crmDealerDashMachines: 'Maszyny', crmDealerDashDetails: 'Szczegóły zamówień i rabatów', crmDealerDashDetailsNote: 'Dane kanoniczne ze złożonych zamówień i zamrożonych migawek cen.', crmDealerDashRows: '{count} wierszy', crmDealerDashNoMatchingRows: 'Żaden wiersz nie pasuje do filtrów.', crmDealerDashOrderNo: 'Nr zamówienia', crmDealerDashQuoteNo: 'Nr oferty', crmDealerDashDate: 'Data', crmDealerDashMachine: 'Maszyna', crmDealerDashListPrice: 'Cena katalogowa', crmDealerDashExtraAmount: 'Kwota dodatkowa', crmDealerDashPaymentDeliveryAmount: 'Kwota płatności/dostawy', crmDealerDashDiscountTotal: 'Rabat łącznie', crmDealerDashNet: 'Netto', crmDealerDashLoadError: 'Nie udało się załadować danych dashboardu: {error}', crmDealerDashLoading: 'Ładowanie danych dashboardu…',
  crmDealerDashPartnerSalesContacts: 'Dane partnera: kontakty sprzedażowe. Brak kontaktu jest oznaczony jako Brak informacji.', crmDealerDashGrossMargin: 'Marża', crmDealerDashLocalScope: 'Lokalna symulacja zakresu', crmDealerDashScopeNote: 'Filtry są budowane z zakresu, dlatego mogą tylko zawężać dane.', crmDealerDashLocalRows: 'Lokalny prototyp · {count} wierszy w zakresie',
};

const cs: Dict = {
  ...en,
  crmDealerDashPartnerList: 'Seznam partnerů', crmDealerDashQuickSelect: 'Rychlý výběr', crmDealerDashToday: 'Dnes', crmDealerDashThisMonth: 'Tento měsíc', crmDealerDashThisQuarter: 'Toto čtvrtletí', crmDealerDashThisYear: 'Tento rok', crmDealerDashLastYear: 'Minulý rok', crmDealerDashAll: 'Vše', crmDealerDashReset: 'Obnovit', crmDealerDashExport: 'Exportovat', crmDealerDashPeriod: 'Období', crmDealerDashDateFrom: 'Datum od', crmDealerDashDateTo: 'Datum do', crmDealerDashYearFrom: 'Rok od', crmDealerDashYearTo: 'Rok do', crmDealerDashAllYears: 'Všechny roky',
  crmDealerDashCountry: 'Země', crmDealerDashSeller: 'Prodejce', crmDealerDashDealer: 'Dealer', crmDealerDashCustomer: 'Zákazník', crmDealerDashMachineModel: 'Stroj / model', crmDealerDashPartnerType: 'Typ partnera', crmDealerDashImporter: 'Importér', crmDealerDashServicePartner: 'Servisní partner', crmDealerDashSelected: 'Vybráno: {count}', crmDealerDashSearch: 'Hledat {label}...', crmDealerDashCurrency: 'Měna', crmDealerDashBoth: 'Obě', crmDealerDashMoreFilters: 'Další filtry', crmDealerDashDatePriority: 'Datum má přednost', crmDealerDashCanonicalRows: '{count} kanonických řádků',
  crmDealerDashTotalRevenue: 'Celkové tržby', crmDealerDashOrderCount: 'Počet objednávek', crmDealerDashMachinesSold: 'Prodané stroje', crmDealerDashAverageDiscount: 'Průměrná sleva', crmDealerDashExtraDiscountTotal: 'Celková dodatečná sleva', crmDealerDashPaymentDeliveryDiscount: 'Sleva za platbu/dodání', crmDealerDashTopCountry: 'Nejlepší země', crmDealerDashTopDealer: 'Nejlepší dealer', crmDealerDashSubmittedOrders: 'Odeslané objednávky', crmDealerDashMachinesTotal: 'Stroje celkem', crmDealerDashTotalDiscount: 'Celková sleva', crmDealerDashNormalizedDkk: 'Normalizováno do DKK pro kombinované zobrazení', crmDealerDashShownIn: 'Zobrazeno v {currency}', crmDealerDashUnavailable: 'Není k dispozici', crmDealerDashMissingRows: '{count} objednávek bez kanonických detailů slev', crmDealerDashNoData: 'Žádná data',
  crmDealerDashRevenueOverTime: 'Tržby v čase', crmDealerDashRevenueByYear: 'Tržby podle kalendářního roku', crmDealerDashTopTenDealers: 'Top 10 dealerů', crmDealerDashRevenueByCountry: 'Tržby podle země', crmDealerDashRevenueBySeller: 'Tržby podle prodejce', crmDealerDashMachineSalesUnits: 'Prodej strojů (ks)', crmDealerDashMachineSalesValue: 'Hodnota prodeje strojů', crmDealerDashDkVsDeRevenue: 'DK vs DE - tržby', crmDealerDashDiscountByMachine: 'Rozdělení slev podle stroje', crmDealerDashAverageDiscountOverTime: 'Průměrná sleva v čase', crmDealerDashDiscountValueByYear: 'Hodnota slev podle roku', crmDealerDashClickBar: 'Kliknutím na sloupec filtrujete', crmDealerDashSelectedPeriod: 'Celkem ve vybraném období', crmDealerDashAnnualDistribution: 'Roční rozdělení', crmDealerDashAveragePercent: 'Průměr v procentech', crmDealerDashEmptyChart: 'Ve vybraném rozsahu nejsou data.',
  crmDealerDashStandard: 'Standardní', crmDealerDashExtra: 'Dodatečná', crmDealerDashPaymentDelivery: 'Platba/dodání', crmDealerDashCombined: 'Celkem', crmDealerDashRevenue: 'Tržby', crmDealerDashMachines: 'Stroje', crmDealerDashDetails: 'Podrobnosti objednávek a slev', crmDealerDashDetailsNote: 'Kanonická data z odeslaných objednávek a zmrazených cenových snímků.', crmDealerDashRows: '{count} řádků', crmDealerDashNoMatchingRows: 'Filtrům neodpovídají žádné řádky.', crmDealerDashOrderNo: 'Č. objednávky', crmDealerDashQuoteNo: 'Č. nabídky', crmDealerDashDate: 'Datum', crmDealerDashMachine: 'Stroj', crmDealerDashListPrice: 'Ceníková cena', crmDealerDashExtraAmount: 'Dodatečná částka', crmDealerDashPaymentDeliveryAmount: 'Částka platba/dodání', crmDealerDashDiscountTotal: 'Sleva celkem', crmDealerDashNet: 'Netto', crmDealerDashLoadError: 'Data dashboardu se nepodařilo načíst: {error}', crmDealerDashLoading: 'Načítání dat dashboardu…',
  crmDealerDashPartnerSalesContacts: 'Partnerská data: obchodní kontakty. Chybějící kontakt se zobrazí jako Chybějící informace.', crmDealerDashGrossMargin: 'Marže', crmDealerDashLocalScope: 'Místní simulace rozsahu', crmDealerDashScopeNote: 'Filtry vycházejí z rozsahu, a proto mohou data pouze zúžit.', crmDealerDashLocalRows: 'Místní prototyp · {count} řádků v rozsahu',
};

export const CRM_DEALER_DASHBOARD_TRANSLATIONS: Record<PortalUiLanguage, Dict> = {
  da, en, de, it, hu, sv, fr, pl, cs,
};
