import type { PortalUiLanguage } from '@/lib/portalLanguages';

export interface SupportAdminCopy {
  title: string;
  subtitle: string;
  backendOnly: string;
  overview: string;
  questions: string;
  unanswered: string;
  feedback: string;
  knowledgeBase: string;
  observability: string;
  totalQuestions: string;
  uniqueUsers: string;
  answerRate: string;
  groundedRate: string;
  noAnswerRate: string;
  positiveFeedbackRate: string;
  averageResponseTime: string;
  questionsToday: string;
  questions7Days: string;
  questions30Days: string;
  knowledgeGaps: string;
  approvedKnowledge: string;
  noData: string;
  noQuestions: string;
  noGaps: string;
  noFeedback: string;
  noKnowledge: string;
  search: string;
  all: string;
  language: string;
  category: string;
  machine: string;
  status: string;
  reason: string;
  result: string;
  date: string;
  dateFrom: string;
  dateTo: string;
  productReference: string;
  question: string;
  answer: string;
  userReference: string;
  partnerReference: string;
  role: string;
  route: string;
  sourceReferences: string;
  retrievalStatus: string;
  latency: string;
  technicalError: string;
  occurrenceCount: string;
  firstSeen: string;
  lastSeen: string;
  createKnowledgeDraft: string;
  newKnowledge: string;
  edit: string;
  save: string;
  cancel: string;
  retry: string;
  loading: string;
  titleField: string;
  type: string;
  summary: string;
  content: string;
  keywords: string;
  source: string;
  access: string;
  requiredArea: string;
  requiredModule: string;
  version: string;
  created: string;
  updated: string;
  explicitFeedback: string;
  comment: string;
  totalRequests: string;
  successfulRequests: string;
  failedRequests: string;
  p95Latency: string;
  retrievalLatency: string;
  modelLatency: string;
  providerErrors: string;
  timeouts: string;
  retries: string;
  model: string;
  inputTokens: string;
  outputTokens: string;
  cachedTokens: string;
  estimatedCost: string;
  zeroStateHint: string;
  saveSuccess: string;
  filters: string;
  clearFilters: string;
  openDetails: string;
  confidence: string;
  outcome: string;
  confidenceHigh: string;
  confidenceMedium: string;
  confidenceLow: string;
  confidenceNone: string;
  confidenceUnknown: string;
  clarificationRequests: string;
  sourceConflicts: string;
  staleKnowledgeBlocks: string;
  overdueReviews: string;
  effectiveFrom: string;
  effectiveUntil: string;
  lastReviewed: string;
  nextReview: string;
  assistantConfigurations: string;
  assistantCompleted: string;
  assistantPreviews: string;
  assistantQuotes: string;
  assistantLeads: string;
  assistantPdfs: string;
  assistantEmails: string;
  assistantHandoffs: string;
  assistantFailures: string;
  assistantOpenWorkflows: string;
  timanKnowledgeSync: string;
  syncNow: string;
  syncRunning: string;
  syncComplete: string;
  lastSync: string;
  discoveredSources: string;
  awaitingReview: string;
  indexedSources: string;
  changedSources: string;
  staleSources: string;
  webCandidates: string;
  webFallback30d: string;
  sourceBreakdown: string;
  autoPromotionOff: string;
  languageCoverage: string;
}

const en: SupportAdminCopy = {
  title: 'AI Support', subtitle: 'Questions, knowledge and technical observability for Timan Support.', backendOnly: 'Backend + Support only',
  overview: 'Overview', questions: 'Questions', unanswered: 'Unanswered', feedback: 'Feedback', knowledgeBase: 'Knowledge Base', observability: 'System / Observability',
  totalQuestions: 'Total questions', uniqueUsers: 'Unique users', answerRate: 'Answer rate', groundedRate: 'Grounded answer rate', noAnswerRate: 'No-answer rate', positiveFeedbackRate: 'Positive feedback rate', averageResponseTime: 'Average response time', questionsToday: 'Questions today', questions7Days: 'Questions / 7 days', questions30Days: 'Questions / 30 days', knowledgeGaps: 'Knowledge gaps', approvedKnowledge: 'Approved knowledge',
  noData: 'No data yet', noQuestions: 'No Support questions have been logged.', noGaps: 'No knowledge gaps are open.', noFeedback: 'No explicit feedback has been received.', noKnowledge: 'No knowledge items have been created.', search: 'Search', all: 'All', language: 'Language', category: 'Category', machine: 'Machine', status: 'Status', reason: 'Reason', result: 'Result', date: 'Date', dateFrom: 'From date', dateTo: 'To date', productReference: 'Product reference', question: 'Question', answer: 'Answer', userReference: 'User reference', partnerReference: 'Partner reference', role: 'Role', route: 'Page context', sourceReferences: 'Source references', retrievalStatus: 'Retrieval status', latency: 'Latency', technicalError: 'Technical error', occurrenceCount: 'Occurrences', firstSeen: 'First seen', lastSeen: 'Last seen', createKnowledgeDraft: 'Create knowledge draft', newKnowledge: 'New knowledge item', edit: 'Edit', save: 'Save', cancel: 'Cancel', retry: 'Try again', loading: 'Loading...', titleField: 'Title', type: 'Type', summary: 'Summary', content: 'Content', keywords: 'Keywords', source: 'Source / reference', access: 'Access scope', requiredArea: 'Required area', requiredModule: 'Required module', version: 'Version', created: 'Created', updated: 'Updated', explicitFeedback: 'Explicit feedback', comment: 'Comment', totalRequests: 'Total requests', successfulRequests: 'Successful requests', failedRequests: 'Failed requests', p95Latency: 'P95 latency', retrievalLatency: 'Retrieval latency', modelLatency: 'Model latency', providerErrors: 'Provider errors', timeouts: 'Timeouts', retries: 'Retries', model: 'Model', inputTokens: 'Input tokens', outputTokens: 'Output tokens', cachedTokens: 'Cached tokens', estimatedCost: 'Estimated cost', zeroStateHint: 'No Support runtime events have been recorded yet.', saveSuccess: 'Knowledge item saved.', filters: 'Filters', clearFilters: 'Reset filters', openDetails: 'Open details',
  confidence: 'System confidence', outcome: 'Outcome', confidenceHigh: 'High confidence', confidenceMedium: 'Medium confidence', confidenceLow: 'Low confidence', confidenceNone: 'Unable to answer safely', confidenceUnknown: 'Not evaluated', clarificationRequests: 'Clarification requests', sourceConflicts: 'Source conflicts', staleKnowledgeBlocks: 'Stale-knowledge blocks', overdueReviews: 'Overdue reviews', effectiveFrom: 'Effective from', effectiveUntil: 'Effective until', lastReviewed: 'Last reviewed', nextReview: 'Next review',
  assistantConfigurations: 'Assistant configurations', assistantCompleted: 'Completed configurations', assistantPreviews: 'Quote previews', assistantQuotes: 'Quotes created', assistantLeads: 'Leads created / linked', assistantPdfs: 'PDFs generated', assistantEmails: 'Emails sent', assistantHandoffs: 'Human handoffs', assistantFailures: 'Failed actions', assistantOpenWorkflows: 'Open workflows',
  timanKnowledgeSync: 'Timan.dk Knowledge sync', syncNow: 'Sync now', syncRunning: 'Syncing...', syncComplete: 'Knowledge sync completed.', lastSync: 'Last sync', discoveredSources: 'Discovered sources', awaitingReview: 'Awaiting review', indexedSources: 'Indexed sources', changedSources: 'Changed sources', staleSources: 'Stale / missing', webCandidates: 'Web candidates', webFallback30d: 'Web fallback / 30 days', sourceBreakdown: 'Answer sources / 30 days', autoPromotionOff: 'Automatic promotion is disabled', languageCoverage: 'Language coverage',
};

const da: SupportAdminCopy = {
  ...en,
  subtitle: 'Spørgsmål, viden og teknisk overvågning for Timan Support.', backendOnly: 'Kun Backend + Support', overview: 'Overblik', questions: 'Spørgsmål', unanswered: 'Ubesvarede', feedback: 'Feedback', knowledgeBase: 'Vidensbase', observability: 'System / Overvågning', totalQuestions: 'Spørgsmål i alt', uniqueUsers: 'Unikke brugere', answerRate: 'Svarrate', groundedRate: 'Kildebaseret svarrate', noAnswerRate: 'Ingen-svar-rate', positiveFeedbackRate: 'Positiv feedback-rate', averageResponseTime: 'Gennemsnitlig svartid', questionsToday: 'Spørgsmål i dag', questions7Days: 'Spørgsmål / 7 dage', questions30Days: 'Spørgsmål / 30 dage', knowledgeGaps: 'Videnshuller', approvedKnowledge: 'Godkendt viden', noData: 'Ingen data endnu', noQuestions: 'Der er endnu ikke logget Support-spørgsmål.', noGaps: 'Der er ingen åbne videnshuller.', noFeedback: 'Der er endnu ikke modtaget eksplicit feedback.', noKnowledge: 'Der er endnu ikke oprettet videnselementer.', search: 'Søg', all: 'Alle', language: 'Sprog', category: 'Kategori', machine: 'Maskine', status: 'Status', reason: 'Årsag', result: 'Resultat', date: 'Dato', dateFrom: 'Fra dato', dateTo: 'Til dato', productReference: 'Produktreference', question: 'Spørgsmål', answer: 'Svar', userReference: 'Brugerreference', partnerReference: 'Partnerreference', role: 'Rolle', route: 'Sidekontekst', sourceReferences: 'Kildereferencer', retrievalStatus: 'Søgestatus', latency: 'Svartid', technicalError: 'Teknisk fejl', occurrenceCount: 'Forekomster', firstSeen: 'Først set', lastSeen: 'Senest set', createKnowledgeDraft: 'Opret videnskladde', newKnowledge: 'Nyt videnselement', edit: 'Redigér', save: 'Gem', cancel: 'Annuller', retry: 'Prøv igen', loading: 'Henter...', titleField: 'Titel', type: 'Type', summary: 'Resumé', content: 'Indhold', keywords: 'Nøgleord', source: 'Kilde / reference', access: 'Adgangsomfang', requiredArea: 'Krævet område', requiredModule: 'Krævet modul', version: 'Version', created: 'Oprettet', updated: 'Opdateret', explicitFeedback: 'Eksplicit feedback', comment: 'Kommentar', totalRequests: 'Forespørgsler i alt', successfulRequests: 'Vellykkede forespørgsler', failedRequests: 'Fejlede forespørgsler', p95Latency: 'P95-svartid', retrievalLatency: 'Søgetid', modelLatency: 'Modeltid', providerErrors: 'Providerfejl', timeouts: 'Timeouts', retries: 'Genforsøg', model: 'Model', inputTokens: 'Input-tokens', outputTokens: 'Output-tokens', cachedTokens: 'Cachede tokens', estimatedCost: 'Estimeret pris', zeroStateHint: 'Der er endnu ikke registreret runtime-hændelser fra Support.', saveSuccess: 'Videnselementet er gemt.', filters: 'Filtre', clearFilters: 'Nulstil filtre', openDetails: 'Åbn detaljer',
  assistantConfigurations: 'Assistant-konfigurationer', assistantCompleted: 'Fuldførte konfigurationer', assistantPreviews: 'Prisvisninger', assistantQuotes: 'Oprettede tilbud', assistantLeads: 'Oprettede / tilknyttede leads', assistantPdfs: 'Genererede PDF’er', assistantEmails: 'Sendte mails', assistantHandoffs: 'Menneskelige overdragelser', assistantFailures: 'Fejlede handlinger', assistantOpenWorkflows: 'Åbne workflows',
  timanKnowledgeSync: 'Timan.dk videnssync', syncNow: 'Synkronisér nu', syncRunning: 'Synkroniserer...', syncComplete: 'Videnssync er gennemført.', lastSync: 'Seneste sync', discoveredSources: 'Fundne kilder', awaitingReview: 'Afventer gennemgang', indexedSources: 'Indekserede kilder', changedSources: 'Ændrede kilder', staleSources: 'Forældede / manglende', webCandidates: 'Webkandidater', webFallback30d: 'Webfallback / 30 dage', sourceBreakdown: 'Svarkilder / 30 dage', autoPromotionOff: 'Automatisk godkendelse er slået fra', languageCoverage: 'Sprogdækning',
};

const de: SupportAdminCopy = {
  ...en,
  subtitle: 'Fragen, Wissen und technische Beobachtbarkeit für Timan Support.', backendOnly: 'Nur Backend + Support', overview: 'Übersicht', questions: 'Fragen', unanswered: 'Unbeantwortet', feedback: 'Feedback', knowledgeBase: 'Wissensbasis', observability: 'System / Beobachtbarkeit', totalQuestions: 'Fragen insgesamt', uniqueUsers: 'Eindeutige Benutzer', answerRate: 'Antwortrate', groundedRate: 'Quellenbasierte Antwortrate', noAnswerRate: 'Keine-Antwort-Rate', positiveFeedbackRate: 'Positive Feedbackrate', averageResponseTime: 'Durchschnittliche Antwortzeit', questionsToday: 'Fragen heute', questions7Days: 'Fragen / 7 Tage', questions30Days: 'Fragen / 30 Tage', knowledgeGaps: 'Wissenslücken', approvedKnowledge: 'Freigegebenes Wissen', noData: 'Noch keine Daten', noQuestions: 'Es wurden noch keine Supportfragen protokolliert.', noGaps: 'Keine offenen Wissenslücken.', noFeedback: 'Noch kein ausdrückliches Feedback.', noKnowledge: 'Noch keine Wissenseinträge.', search: 'Suchen', all: 'Alle', language: 'Sprache', category: 'Kategorie', machine: 'Maschine', status: 'Status', reason: 'Grund', result: 'Ergebnis', date: 'Datum', dateFrom: 'Von Datum', dateTo: 'Bis Datum', productReference: 'Produktreferenz', question: 'Frage', answer: 'Antwort', userReference: 'Benutzerreferenz', partnerReference: 'Partnerreferenz', role: 'Rolle', route: 'Seitenkontext', sourceReferences: 'Quellenreferenzen', retrievalStatus: 'Abrufstatus', latency: 'Latenz', technicalError: 'Technischer Fehler', occurrenceCount: 'Vorkommen', firstSeen: 'Zuerst gesehen', lastSeen: 'Zuletzt gesehen', createKnowledgeDraft: 'Wissensentwurf erstellen', newKnowledge: 'Neuer Wissenseintrag', edit: 'Bearbeiten', save: 'Speichern', cancel: 'Abbrechen', retry: 'Erneut versuchen', loading: 'Wird geladen...', titleField: 'Titel', type: 'Typ', summary: 'Zusammenfassung', content: 'Inhalt', keywords: 'Schlüsselwörter', source: 'Quelle / Referenz', access: 'Zugriffsbereich', requiredArea: 'Erforderlicher Bereich', requiredModule: 'Erforderliches Modul', version: 'Version', created: 'Erstellt', updated: 'Aktualisiert', explicitFeedback: 'Ausdrückliches Feedback', comment: 'Kommentar', totalRequests: 'Anfragen insgesamt', successfulRequests: 'Erfolgreiche Anfragen', failedRequests: 'Fehlgeschlagene Anfragen', p95Latency: 'P95-Latenz', retrievalLatency: 'Abruflatenz', modelLatency: 'Modelllatenz', providerErrors: 'Providerfehler', timeouts: 'Zeitüberschreitungen', retries: 'Wiederholungen', model: 'Modell', inputTokens: 'Eingabe-Tokens', outputTokens: 'Ausgabe-Tokens', cachedTokens: 'Zwischengespeicherte Tokens', estimatedCost: 'Geschätzte Kosten', zeroStateHint: 'Es wurden noch keine Support-Laufzeitereignisse erfasst.', saveSuccess: 'Wissenseintrag gespeichert.', filters: 'Filter', clearFilters: 'Filter zurücksetzen', openDetails: 'Details öffnen',
};

const it: SupportAdminCopy = { ...en, subtitle: 'Domande, conoscenze e osservabilità tecnica per Timan Support.', backendOnly: 'Solo Backend + Support', overview: 'Panoramica', questions: 'Domande', unanswered: 'Senza risposta', knowledgeBase: 'Base di conoscenza', observability: 'Sistema / Osservabilità', totalQuestions: 'Domande totali', uniqueUsers: 'Utenti unici', answerRate: 'Tasso di risposta', groundedRate: 'Risposte basate su fonti', noAnswerRate: 'Tasso senza risposta', positiveFeedbackRate: 'Feedback positivo', averageResponseTime: 'Tempo medio di risposta', questionsToday: 'Domande oggi', questions7Days: 'Domande / 7 giorni', questions30Days: 'Domande / 30 giorni', knowledgeGaps: 'Lacune di conoscenza', approvedKnowledge: 'Conoscenza approvata', noData: 'Nessun dato', noQuestions: 'Nessuna domanda Support registrata.', noGaps: 'Nessuna lacuna aperta.', noFeedback: 'Nessun feedback esplicito.', noKnowledge: 'Nessun elemento di conoscenza.', search: 'Cerca', all: 'Tutti', language: 'Lingua', category: 'Categoria', machine: 'Macchina', reason: 'Motivo', result: 'Risultato', date: 'Data', question: 'Domanda', answer: 'Risposta', userReference: 'Riferimento utente', partnerReference: 'Riferimento partner', role: 'Ruolo', route: 'Contesto pagina', sourceReferences: 'Riferimenti fonte', retrievalStatus: 'Stato recupero', latency: 'Latenza', technicalError: 'Errore tecnico', occurrenceCount: 'Occorrenze', firstSeen: 'Prima rilevazione', lastSeen: 'Ultima rilevazione', createKnowledgeDraft: 'Crea bozza conoscenza', newKnowledge: 'Nuovo elemento', edit: 'Modifica', save: 'Salva', cancel: 'Annulla', retry: 'Riprova', loading: 'Caricamento...', titleField: 'Titolo', type: 'Tipo', summary: 'Riepilogo', content: 'Contenuto', keywords: 'Parole chiave', source: 'Fonte / riferimento', access: 'Ambito accesso', requiredArea: 'Area richiesta', requiredModule: 'Modulo richiesto', version: 'Versione', created: 'Creato', updated: 'Aggiornato', explicitFeedback: 'Feedback esplicito', comment: 'Commento', totalRequests: 'Richieste totali', successfulRequests: 'Richieste riuscite', failedRequests: 'Richieste fallite', p95Latency: 'Latenza P95', retrievalLatency: 'Latenza recupero', modelLatency: 'Latenza modello', providerErrors: 'Errori provider', timeouts: 'Timeout', retries: 'Tentativi', model: 'Modello', inputTokens: 'Token input', outputTokens: 'Token output', cachedTokens: 'Token in cache', estimatedCost: 'Costo stimato', zeroStateHint: 'Non sono ancora stati registrati eventi runtime di Support.', saveSuccess: 'Elemento salvato.', filters: 'Filtri', clearFilters: 'Azzera filtri', openDetails: 'Apri dettagli' };

const hu: SupportAdminCopy = { ...en, subtitle: 'Kérdések, tudás és műszaki megfigyelhetőség a Timan Support számára.', backendOnly: 'Csak Backend + Support', overview: 'Áttekintés', questions: 'Kérdések', unanswered: 'Megválaszolatlan', feedback: 'Visszajelzés', knowledgeBase: 'Tudásbázis', observability: 'Rendszer / Megfigyelés', totalQuestions: 'Összes kérdés', uniqueUsers: 'Egyedi felhasználók', answerRate: 'Válaszadási arány', groundedRate: 'Forrásalapú válaszok', noAnswerRate: 'Válasz nélküli arány', positiveFeedbackRate: 'Pozitív visszajelzés', averageResponseTime: 'Átlagos válaszidő', questionsToday: 'Mai kérdések', questions7Days: 'Kérdések / 7 nap', questions30Days: 'Kérdések / 30 nap', knowledgeGaps: 'Tudáshiányok', approvedKnowledge: 'Jóváhagyott tudás', noData: 'Még nincs adat', noQuestions: 'Még nincs naplózott Support-kérdés.', noGaps: 'Nincs nyitott tudáshiány.', noFeedback: 'Még nincs kifejezett visszajelzés.', noKnowledge: 'Még nincs tudáselem.', search: 'Keresés', all: 'Mind', language: 'Nyelv', category: 'Kategória', machine: 'Gép', status: 'Állapot', reason: 'Ok', result: 'Eredmény', date: 'Dátum', question: 'Kérdés', answer: 'Válasz', userReference: 'Felhasználói hivatkozás', partnerReference: 'Partnerhivatkozás', role: 'Szerepkör', route: 'Oldalkontextus', sourceReferences: 'Forráshivatkozások', retrievalStatus: 'Lekérési állapot', latency: 'Késleltetés', technicalError: 'Műszaki hiba', occurrenceCount: 'Előfordulás', firstSeen: 'Első észlelés', lastSeen: 'Utolsó észlelés', createKnowledgeDraft: 'Tudásvázlat létrehozása', newKnowledge: 'Új tudáselem', edit: 'Szerkesztés', save: 'Mentés', cancel: 'Mégse', retry: 'Újra', loading: 'Betöltés...', titleField: 'Cím', type: 'Típus', summary: 'Összefoglaló', content: 'Tartalom', keywords: 'Kulcsszavak', source: 'Forrás / hivatkozás', access: 'Hozzáférési kör', requiredArea: 'Szükséges terület', requiredModule: 'Szükséges modul', version: 'Verzió', created: 'Létrehozva', updated: 'Frissítve', explicitFeedback: 'Kifejezett visszajelzés', comment: 'Megjegyzés', totalRequests: 'Összes kérés', successfulRequests: 'Sikeres kérések', failedRequests: 'Sikertelen kérések', p95Latency: 'P95 késleltetés', retrievalLatency: 'Lekérési késleltetés', modelLatency: 'Modell késleltetés', providerErrors: 'Szolgáltatói hibák', timeouts: 'Időtúllépések', retries: 'Újrapróbálások', model: 'Modell', inputTokens: 'Bemeneti tokenek', outputTokens: 'Kimeneti tokenek', cachedTokens: 'Gyorsítótárazott tokenek', estimatedCost: 'Becsült költség', zeroStateHint: 'Még nem került rögzítésre Support-futásidejű esemény.', saveSuccess: 'Tudáselem mentve.', filters: 'Szűrők', clearFilters: 'Szűrők törlése', openDetails: 'Részletek' };

const sv: SupportAdminCopy = { ...en, subtitle: 'Frågor, kunskap och teknisk observerbarhet för Timan Support.', backendOnly: 'Endast Backend + Support', overview: 'Översikt', questions: 'Frågor', unanswered: 'Obesvarade', feedback: 'Feedback', knowledgeBase: 'Kunskapsbas', observability: 'System / Observerbarhet', totalQuestions: 'Totalt antal frågor', uniqueUsers: 'Unika användare', answerRate: 'Svarsfrekvens', groundedRate: 'Källbaserad svarsfrekvens', noAnswerRate: 'Ingen-svar-frekvens', positiveFeedbackRate: 'Positiv feedback', averageResponseTime: 'Genomsnittlig svarstid', questionsToday: 'Frågor idag', questions7Days: 'Frågor / 7 dagar', questions30Days: 'Frågor / 30 dagar', knowledgeGaps: 'Kunskapsluckor', approvedKnowledge: 'Godkänd kunskap', noData: 'Inga data ännu', noQuestions: 'Inga Support-frågor har loggats.', noGaps: 'Inga öppna kunskapsluckor.', noFeedback: 'Ingen uttrycklig feedback ännu.', noKnowledge: 'Inga kunskapsposter ännu.', search: 'Sök', all: 'Alla', language: 'Språk', category: 'Kategori', machine: 'Maskin', status: 'Status', reason: 'Orsak', result: 'Resultat', date: 'Datum', question: 'Fråga', answer: 'Svar', userReference: 'Användarreferens', partnerReference: 'Partnerreferens', role: 'Roll', route: 'Sidkontext', sourceReferences: 'Källreferenser', retrievalStatus: 'Hämtningsstatus', latency: 'Svarstid', technicalError: 'Tekniskt fel', occurrenceCount: 'Förekomster', firstSeen: 'Först sedd', lastSeen: 'Senast sedd', createKnowledgeDraft: 'Skapa kunskapsutkast', newKnowledge: 'Ny kunskapspost', edit: 'Redigera', save: 'Spara', cancel: 'Avbryt', retry: 'Försök igen', loading: 'Laddar...', titleField: 'Titel', type: 'Typ', summary: 'Sammanfattning', content: 'Innehåll', keywords: 'Nyckelord', source: 'Källa / referens', access: 'Åtkomstomfång', requiredArea: 'Krävt område', requiredModule: 'Krävd modul', version: 'Version', created: 'Skapad', updated: 'Uppdaterad', explicitFeedback: 'Uttrycklig feedback', comment: 'Kommentar', totalRequests: 'Totala förfrågningar', successfulRequests: 'Lyckade förfrågningar', failedRequests: 'Misslyckade förfrågningar', p95Latency: 'P95-svarstid', retrievalLatency: 'Hämtningslatens', modelLatency: 'Modellatens', providerErrors: 'Leverantörsfel', timeouts: 'Tidsgränser', retries: 'Återförsök', model: 'Modell', inputTokens: 'Indatatokens', outputTokens: 'Utdatatokens', cachedTokens: 'Cachade tokens', estimatedCost: 'Beräknad kostnad', zeroStateHint: 'Inga runtime-händelser från Support har registrerats ännu.', saveSuccess: 'Kunskapsposten har sparats.', filters: 'Filter', clearFilters: 'Återställ filter', openDetails: 'Öppna detaljer' };

const fr: SupportAdminCopy = { ...en, subtitle: 'Questions, connaissances et observabilité technique pour Timan Support.', backendOnly: 'Backend + Support uniquement', overview: 'Vue d’ensemble', questions: 'Questions', unanswered: 'Sans réponse', feedback: 'Retours', knowledgeBase: 'Base de connaissances', observability: 'Système / Observabilité', totalQuestions: 'Questions totales', uniqueUsers: 'Utilisateurs uniques', answerRate: 'Taux de réponse', groundedRate: 'Réponses fondées sur des sources', noAnswerRate: 'Taux sans réponse', positiveFeedbackRate: 'Retours positifs', averageResponseTime: 'Temps de réponse moyen', questionsToday: 'Questions aujourd’hui', questions7Days: 'Questions / 7 jours', questions30Days: 'Questions / 30 jours', knowledgeGaps: 'Lacunes de connaissances', approvedKnowledge: 'Connaissances approuvées', noData: 'Aucune donnée', noQuestions: 'Aucune question Support enregistrée.', noGaps: 'Aucune lacune ouverte.', noFeedback: 'Aucun retour explicite.', noKnowledge: 'Aucun élément de connaissance.', search: 'Rechercher', all: 'Tous', language: 'Langue', category: 'Catégorie', machine: 'Machine', status: 'Statut', reason: 'Raison', result: 'Résultat', date: 'Date', question: 'Question', answer: 'Réponse', userReference: 'Référence utilisateur', partnerReference: 'Référence partenaire', role: 'Rôle', route: 'Contexte de page', sourceReferences: 'Références sources', retrievalStatus: 'État de recherche', latency: 'Latence', technicalError: 'Erreur technique', occurrenceCount: 'Occurrences', firstSeen: 'Première occurrence', lastSeen: 'Dernière occurrence', createKnowledgeDraft: 'Créer un brouillon', newKnowledge: 'Nouvel élément', edit: 'Modifier', save: 'Enregistrer', cancel: 'Annuler', retry: 'Réessayer', loading: 'Chargement...', titleField: 'Titre', type: 'Type', summary: 'Résumé', content: 'Contenu', keywords: 'Mots-clés', source: 'Source / référence', access: 'Portée d’accès', requiredArea: 'Zone requise', requiredModule: 'Module requis', version: 'Version', created: 'Créé', updated: 'Mis à jour', explicitFeedback: 'Retour explicite', comment: 'Commentaire', totalRequests: 'Requêtes totales', successfulRequests: 'Requêtes réussies', failedRequests: 'Requêtes échouées', p95Latency: 'Latence P95', retrievalLatency: 'Latence de recherche', modelLatency: 'Latence modèle', providerErrors: 'Erreurs fournisseur', timeouts: 'Délais dépassés', retries: 'Nouvelles tentatives', model: 'Modèle', inputTokens: 'Jetons d’entrée', outputTokens: 'Jetons de sortie', cachedTokens: 'Jetons en cache', estimatedCost: 'Coût estimé', zeroStateHint: 'Aucun événement d’exécution Support n’a encore été enregistré.', saveSuccess: 'Élément enregistré.', filters: 'Filtres', clearFilters: 'Réinitialiser', openDetails: 'Ouvrir les détails' };

const pl: SupportAdminCopy = { ...en, subtitle: 'Pytania, wiedza i obserwowalność techniczna dla Timan Support.', backendOnly: 'Tylko Backend + Support', overview: 'Przegląd', questions: 'Pytania', unanswered: 'Bez odpowiedzi', feedback: 'Opinie', knowledgeBase: 'Baza wiedzy', observability: 'System / Obserwowalność', totalQuestions: 'Wszystkie pytania', uniqueUsers: 'Unikalni użytkownicy', answerRate: 'Wskaźnik odpowiedzi', groundedRate: 'Odpowiedzi oparte na źródłach', noAnswerRate: 'Brak odpowiedzi', positiveFeedbackRate: 'Pozytywne opinie', averageResponseTime: 'Średni czas odpowiedzi', questionsToday: 'Pytania dzisiaj', questions7Days: 'Pytania / 7 dni', questions30Days: 'Pytania / 30 dni', knowledgeGaps: 'Luki w wiedzy', approvedKnowledge: 'Zatwierdzona wiedza', noData: 'Brak danych', noQuestions: 'Nie zapisano pytań Support.', noGaps: 'Brak otwartych luk.', noFeedback: 'Brak wyraźnych opinii.', noKnowledge: 'Brak elementów wiedzy.', search: 'Szukaj', all: 'Wszystkie', language: 'Język', category: 'Kategoria', machine: 'Maszyna', status: 'Status', reason: 'Powód', result: 'Wynik', date: 'Data', question: 'Pytanie', answer: 'Odpowiedź', userReference: 'Identyfikator użytkownika', partnerReference: 'Identyfikator partnera', role: 'Rola', route: 'Kontekst strony', sourceReferences: 'Odwołania do źródeł', retrievalStatus: 'Status wyszukiwania', latency: 'Opóźnienie', technicalError: 'Błąd techniczny', occurrenceCount: 'Wystąpienia', firstSeen: 'Pierwsze wystąpienie', lastSeen: 'Ostatnie wystąpienie', createKnowledgeDraft: 'Utwórz szkic wiedzy', newKnowledge: 'Nowy element wiedzy', edit: 'Edytuj', save: 'Zapisz', cancel: 'Anuluj', retry: 'Spróbuj ponownie', loading: 'Ładowanie...', titleField: 'Tytuł', type: 'Typ', summary: 'Podsumowanie', content: 'Treść', keywords: 'Słowa kluczowe', source: 'Źródło / odniesienie', access: 'Zakres dostępu', requiredArea: 'Wymagany obszar', requiredModule: 'Wymagany moduł', version: 'Wersja', created: 'Utworzono', updated: 'Zaktualizowano', explicitFeedback: 'Wyraźna opinia', comment: 'Komentarz', totalRequests: 'Wszystkie żądania', successfulRequests: 'Udane żądania', failedRequests: 'Nieudane żądania', p95Latency: 'Opóźnienie P95', retrievalLatency: 'Opóźnienie wyszukiwania', modelLatency: 'Opóźnienie modelu', providerErrors: 'Błędy dostawcy', timeouts: 'Przekroczenia czasu', retries: 'Ponowienia', model: 'Model', inputTokens: 'Tokeny wejściowe', outputTokens: 'Tokeny wyjściowe', cachedTokens: 'Tokeny z pamięci', estimatedCost: 'Szacowany koszt', zeroStateHint: 'Nie zarejestrowano jeszcze zdarzeń wykonawczych Support.', saveSuccess: 'Element wiedzy zapisany.', filters: 'Filtry', clearFilters: 'Resetuj filtry', openDetails: 'Otwórz szczegóły' };

const cs: SupportAdminCopy = { ...en, subtitle: 'Dotazy, znalosti a technická pozorovatelnost pro Timan Support.', backendOnly: 'Pouze Backend + Support', overview: 'Přehled', questions: 'Dotazy', unanswered: 'Nezodpovězené', feedback: 'Zpětná vazba', knowledgeBase: 'Znalostní báze', observability: 'Systém / Pozorovatelnost', totalQuestions: 'Dotazy celkem', uniqueUsers: 'Jedineční uživatelé', answerRate: 'Míra odpovědí', groundedRate: 'Odpovědi založené na zdrojích', noAnswerRate: 'Míra bez odpovědi', positiveFeedbackRate: 'Pozitivní zpětná vazba', averageResponseTime: 'Průměrná doba odpovědi', questionsToday: 'Dotazy dnes', questions7Days: 'Dotazy / 7 dní', questions30Days: 'Dotazy / 30 dní', knowledgeGaps: 'Mezery ve znalostech', approvedKnowledge: 'Schválené znalosti', noData: 'Zatím žádná data', noQuestions: 'Nebyly zaznamenány žádné dotazy Support.', noGaps: 'Žádné otevřené mezery.', noFeedback: 'Žádná výslovná zpětná vazba.', noKnowledge: 'Žádné znalostní položky.', search: 'Hledat', all: 'Vše', language: 'Jazyk', category: 'Kategorie', machine: 'Stroj', status: 'Stav', reason: 'Důvod', result: 'Výsledek', date: 'Datum', question: 'Dotaz', answer: 'Odpověď', userReference: 'Reference uživatele', partnerReference: 'Reference partnera', role: 'Role', route: 'Kontext stránky', sourceReferences: 'Reference zdrojů', retrievalStatus: 'Stav vyhledání', latency: 'Latence', technicalError: 'Technická chyba', occurrenceCount: 'Výskyty', firstSeen: 'První výskyt', lastSeen: 'Poslední výskyt', createKnowledgeDraft: 'Vytvořit koncept znalosti', newKnowledge: 'Nová znalostní položka', edit: 'Upravit', save: 'Uložit', cancel: 'Zrušit', retry: 'Zkusit znovu', loading: 'Načítání...', titleField: 'Název', type: 'Typ', summary: 'Shrnutí', content: 'Obsah', keywords: 'Klíčová slova', source: 'Zdroj / reference', access: 'Rozsah přístupu', requiredArea: 'Požadovaná oblast', requiredModule: 'Požadovaný modul', version: 'Verze', created: 'Vytvořeno', updated: 'Aktualizováno', explicitFeedback: 'Výslovná zpětná vazba', comment: 'Komentář', totalRequests: 'Požadavky celkem', successfulRequests: 'Úspěšné požadavky', failedRequests: 'Neúspěšné požadavky', p95Latency: 'Latence P95', retrievalLatency: 'Latence vyhledání', modelLatency: 'Latence modelu', providerErrors: 'Chyby poskytovatele', timeouts: 'Časové limity', retries: 'Opakování', model: 'Model', inputTokens: 'Vstupní tokeny', outputTokens: 'Výstupní tokeny', cachedTokens: 'Tokeny v mezipaměti', estimatedCost: 'Odhadované náklady', zeroStateHint: 'Dosud nebyly zaznamenány žádné runtime události Support.', saveSuccess: 'Znalostní položka uložena.', filters: 'Filtry', clearFilters: 'Obnovit filtry', openDetails: 'Otevřít podrobnosti' };

Object.assign(da, { confidence: 'Systemsikkerhed', outcome: 'Udfald', confidenceHigh: 'Høj sikkerhed', confidenceMedium: 'Middel sikkerhed', confidenceLow: 'Lav sikkerhed', confidenceNone: 'Kan ikke besvares sikkert', confidenceUnknown: 'Ikke evalueret', clarificationRequests: 'Afklaringsspørgsmål', sourceConflicts: 'Kildekonflikter', staleKnowledgeBlocks: 'Blokeret forældet viden', overdueReviews: 'Forfaldne gennemgange', effectiveFrom: 'Gyldig fra', effectiveUntil: 'Gyldig til', lastReviewed: 'Senest gennemgået', nextReview: 'Næste gennemgang' });
Object.assign(de, { confidence: 'Systemsicherheit', outcome: 'Ergebnis', confidenceHigh: 'Hohe Sicherheit', confidenceMedium: 'Mittlere Sicherheit', confidenceLow: 'Geringe Sicherheit', confidenceNone: 'Keine sichere Antwort', confidenceUnknown: 'Nicht bewertet', clarificationRequests: 'Rückfragen', sourceConflicts: 'Quellenkonflikte', staleKnowledgeBlocks: 'Blockiertes veraltetes Wissen', overdueReviews: 'Überfällige Prüfungen', effectiveFrom: 'Gültig ab', effectiveUntil: 'Gültig bis', lastReviewed: 'Zuletzt geprüft', nextReview: 'Nächste Prüfung' });
Object.assign(it, { dateFrom: 'Data da', dateTo: 'Data a', productReference: 'Riferimento prodotto', confidence: 'Affidabilità del sistema', outcome: 'Esito', confidenceHigh: 'Affidabilità alta', confidenceMedium: 'Affidabilità media', confidenceLow: 'Affidabilità bassa', confidenceNone: 'Risposta sicura non disponibile', confidenceUnknown: 'Non valutato', clarificationRequests: 'Richieste di chiarimento', sourceConflicts: 'Conflitti tra fonti', staleKnowledgeBlocks: 'Blocchi per conoscenza obsoleta', overdueReviews: 'Revisioni scadute', effectiveFrom: 'Valido dal', effectiveUntil: 'Valido fino al', lastReviewed: 'Ultima revisione', nextReview: 'Prossima revisione' });
Object.assign(hu, { dateFrom: 'Kezdő dátum', dateTo: 'Záró dátum', productReference: 'Termékhivatkozás', confidence: 'Rendszerbizonyosság', outcome: 'Eredmény', confidenceHigh: 'Magas bizonyosság', confidenceMedium: 'Közepes bizonyosság', confidenceLow: 'Alacsony bizonyosság', confidenceNone: 'Nem adható biztonságos válasz', confidenceUnknown: 'Nincs értékelve', clarificationRequests: 'Pontosítási kérések', sourceConflicts: 'Forrásütközések', staleKnowledgeBlocks: 'Elavult tudás blokkolása', overdueReviews: 'Lejárt ellenőrzések', effectiveFrom: 'Érvényes ettől', effectiveUntil: 'Érvényes eddig', lastReviewed: 'Utolsó ellenőrzés', nextReview: 'Következő ellenőrzés' });
Object.assign(sv, { dateFrom: 'Från datum', dateTo: 'Till datum', productReference: 'Produktreferens', confidence: 'Systemsäkerhet', outcome: 'Utfall', confidenceHigh: 'Hög säkerhet', confidenceMedium: 'Medelhög säkerhet', confidenceLow: 'Låg säkerhet', confidenceNone: 'Kan inte svara säkert', confidenceUnknown: 'Inte utvärderad', clarificationRequests: 'Förtydliganden', sourceConflicts: 'Källkonflikter', staleKnowledgeBlocks: 'Blockerad inaktuell kunskap', overdueReviews: 'Försenade granskningar', effectiveFrom: 'Gäller från', effectiveUntil: 'Gäller till', lastReviewed: 'Senast granskad', nextReview: 'Nästa granskning' });
Object.assign(fr, { dateFrom: 'Date de début', dateTo: 'Date de fin', productReference: 'Référence produit', confidence: 'Confiance système', outcome: 'Résultat', confidenceHigh: 'Confiance élevée', confidenceMedium: 'Confiance moyenne', confidenceLow: 'Confiance faible', confidenceNone: 'Réponse sûre impossible', confidenceUnknown: 'Non évalué', clarificationRequests: 'Demandes de précision', sourceConflicts: 'Conflits de sources', staleKnowledgeBlocks: 'Connaissances obsolètes bloquées', overdueReviews: 'Révisions en retard', effectiveFrom: 'Valable à partir du', effectiveUntil: "Valable jusqu'au", lastReviewed: 'Dernière révision', nextReview: 'Prochaine révision' });
Object.assign(pl, { dateFrom: 'Data od', dateTo: 'Data do', productReference: 'Odwołanie produktu', confidence: 'Pewność systemu', outcome: 'Wynik', confidenceHigh: 'Wysoka pewność', confidenceMedium: 'Średnia pewność', confidenceLow: 'Niska pewność', confidenceNone: 'Brak bezpiecznej odpowiedzi', confidenceUnknown: 'Nie oceniono', clarificationRequests: 'Prośby o doprecyzowanie', sourceConflicts: 'Konflikty źródeł', staleKnowledgeBlocks: 'Blokady nieaktualnej wiedzy', overdueReviews: 'Zaległe przeglądy', effectiveFrom: 'Obowiązuje od', effectiveUntil: 'Obowiązuje do', lastReviewed: 'Ostatni przegląd', nextReview: 'Następny przegląd' });
Object.assign(cs, { dateFrom: 'Datum od', dateTo: 'Datum do', productReference: 'Reference produktu', confidence: 'Systémová jistota', outcome: 'Výsledek', confidenceHigh: 'Vysoká jistota', confidenceMedium: 'Střední jistota', confidenceLow: 'Nízká jistota', confidenceNone: 'Nelze bezpečně odpovědět', confidenceUnknown: 'Nevyhodnoceno', clarificationRequests: 'Žádosti o upřesnění', sourceConflicts: 'Konflikty zdrojů', staleKnowledgeBlocks: 'Blokace zastaralých znalostí', overdueReviews: 'Kontroly po termínu', effectiveFrom: 'Platí od', effectiveUntil: 'Platí do', lastReviewed: 'Poslední kontrola', nextReview: 'Další kontrola' });

export const SUPPORT_ADMIN_TRANSLATIONS: Record<PortalUiLanguage, SupportAdminCopy> = {
  da, en, de, it, hu, sv, fr, pl, cs,
};

export function getSupportAdminCopy(language: PortalUiLanguage): SupportAdminCopy {
  return SUPPORT_ADMIN_TRANSLATIONS[language] || SUPPORT_ADMIN_TRANSLATIONS.en;
}

const CODE_LABELS: Record<PortalUiLanguage, Record<string, string>> = {
  da: { DRAFT: 'Kladde', REVIEW: 'Gennemgang', APPROVED: 'Godkendt', ARCHIVED: 'Arkiveret', OPEN: 'Åben', REVIEWING: 'Under gennemgang', RESOLVED: 'Løst', DISMISSED: 'Afvist', PENDING: 'Afventer', ANSWERED: 'Besvaret', NO_ANSWER: 'Intet svar', ERROR: 'Fejl', POSITIVE: 'Positiv', NEGATIVE: 'Negativ', NO_RELEVANT_KNOWLEDGE: 'Ingen relevant viden', ACCESS_RESTRICTED: 'Adgang begrænset', LOW_CONFIDENCE: 'Lav sikkerhed', AMBIGUOUS_QUESTION: 'Uklart spørgsmål', MISSING_DOCUMENTATION: 'Manglende dokumentation', RETRIEVAL_ERROR: 'Søgefejl', AI_PROVIDER_ERROR: 'AI-providerfejl', OTHER: 'Andet' },
  en: {},
  de: { DRAFT: 'Entwurf', REVIEW: 'Prüfung', APPROVED: 'Freigegeben', ARCHIVED: 'Archiviert', OPEN: 'Offen', REVIEWING: 'In Prüfung', RESOLVED: 'Gelöst', DISMISSED: 'Verworfen', PENDING: 'Ausstehend', ANSWERED: 'Beantwortet', NO_ANSWER: 'Keine Antwort', ERROR: 'Fehler', POSITIVE: 'Positiv', NEGATIVE: 'Negativ', NO_RELEVANT_KNOWLEDGE: 'Kein relevantes Wissen', ACCESS_RESTRICTED: 'Zugriff eingeschränkt', LOW_CONFIDENCE: 'Geringe Sicherheit', AMBIGUOUS_QUESTION: 'Mehrdeutige Frage', MISSING_DOCUMENTATION: 'Fehlende Dokumentation', RETRIEVAL_ERROR: 'Suchfehler', AI_PROVIDER_ERROR: 'AI-Providerfehler', OTHER: 'Sonstiges' },
  it: { DRAFT: 'Bozza', REVIEW: 'Revisione', APPROVED: 'Approvato', ARCHIVED: 'Archiviato', OPEN: 'Aperto', REVIEWING: 'In revisione', RESOLVED: 'Risolto', DISMISSED: 'Respinto', PENDING: 'In attesa', ANSWERED: 'Risposto', NO_ANSWER: 'Nessuna risposta', ERROR: 'Errore', POSITIVE: 'Positivo', NEGATIVE: 'Negativo' },
  hu: { DRAFT: 'Vázlat', REVIEW: 'Ellenőrzés', APPROVED: 'Jóváhagyott', ARCHIVED: 'Archivált', OPEN: 'Nyitott', REVIEWING: 'Ellenőrzés alatt', RESOLVED: 'Megoldott', DISMISSED: 'Elutasított', PENDING: 'Függőben', ANSWERED: 'Megválaszolt', NO_ANSWER: 'Nincs válasz', ERROR: 'Hiba', POSITIVE: 'Pozitív', NEGATIVE: 'Negatív' },
  sv: { DRAFT: 'Utkast', REVIEW: 'Granskning', APPROVED: 'Godkänd', ARCHIVED: 'Arkiverad', OPEN: 'Öppen', REVIEWING: 'Under granskning', RESOLVED: 'Löst', DISMISSED: 'Avfärdad', PENDING: 'Väntar', ANSWERED: 'Besvarad', NO_ANSWER: 'Inget svar', ERROR: 'Fel', POSITIVE: 'Positiv', NEGATIVE: 'Negativ' },
  fr: { DRAFT: 'Brouillon', REVIEW: 'Révision', APPROVED: 'Approuvé', ARCHIVED: 'Archivé', OPEN: 'Ouvert', REVIEWING: 'En révision', RESOLVED: 'Résolu', DISMISSED: 'Rejeté', PENDING: 'En attente', ANSWERED: 'Répondu', NO_ANSWER: 'Sans réponse', ERROR: 'Erreur', POSITIVE: 'Positif', NEGATIVE: 'Négatif' },
  pl: { DRAFT: 'Szkic', REVIEW: 'Przegląd', APPROVED: 'Zatwierdzony', ARCHIVED: 'Zarchiwizowany', OPEN: 'Otwarty', REVIEWING: 'W przeglądzie', RESOLVED: 'Rozwiązany', DISMISSED: 'Odrzucony', PENDING: 'Oczekuje', ANSWERED: 'Odpowiedziano', NO_ANSWER: 'Brak odpowiedzi', ERROR: 'Błąd', POSITIVE: 'Pozytywna', NEGATIVE: 'Negatywna' },
  cs: { DRAFT: 'Koncept', REVIEW: 'Kontrola', APPROVED: 'Schváleno', ARCHIVED: 'Archivováno', OPEN: 'Otevřeno', REVIEWING: 'V kontrole', RESOLVED: 'Vyřešeno', DISMISSED: 'Zamítnuto', PENDING: 'Čeká', ANSWERED: 'Zodpovězeno', NO_ANSWER: 'Bez odpovědi', ERROR: 'Chyba', POSITIVE: 'Pozitivní', NEGATIVE: 'Negativní' },
};

Object.assign(CODE_LABELS.da, { HIGH: 'Høj', MEDIUM: 'Middel', LOW: 'Lav', NO_GROUNDED_ANSWER: 'Kan ikke besvares sikkert', CAUTIOUS_ANSWER: 'Forsigtigt svar', CLARIFICATION_REQUIRED: 'Afklaring kræves', SOURCE_CONFLICT: 'Kildekonflikt', STALE_KNOWLEDGE: 'Forældet viden', CONTENT_STALE: 'Indhold forældet', INDEX_STALE: 'Indeks forældet', EMBEDDING_STALE: 'Embedding forældet', REVIEW_OVERDUE: 'Gennemgang forfalden' });
Object.assign(CODE_LABELS.en, { HIGH: 'High', MEDIUM: 'Medium', LOW: 'Low', NO_GROUNDED_ANSWER: 'Unable to answer safely', CAUTIOUS_ANSWER: 'Cautious answer', CLARIFICATION_REQUIRED: 'Clarification required', SOURCE_CONFLICT: 'Source conflict', STALE_KNOWLEDGE: 'Knowledge outdated', CONTENT_STALE: 'Content stale', INDEX_STALE: 'Index stale', EMBEDDING_STALE: 'Embedding stale', REVIEW_OVERDUE: 'Review overdue' });
Object.assign(CODE_LABELS.de, { HIGH: 'Hoch', MEDIUM: 'Mittel', LOW: 'Niedrig', NO_GROUNDED_ANSWER: 'Keine sichere Antwort', CAUTIOUS_ANSWER: 'Vorsichtige Antwort', CLARIFICATION_REQUIRED: 'Rückfrage erforderlich', SOURCE_CONFLICT: 'Quellenkonflikt', STALE_KNOWLEDGE: 'Veraltetes Wissen', CONTENT_STALE: 'Inhalt veraltet', INDEX_STALE: 'Index veraltet', EMBEDDING_STALE: 'Embedding veraltet', REVIEW_OVERDUE: 'Prüfung überfällig' });
Object.assign(CODE_LABELS.it, { HIGH: 'Alta', MEDIUM: 'Media', LOW: 'Bassa', NO_GROUNDED_ANSWER: 'Risposta sicura non disponibile', CAUTIOUS_ANSWER: 'Risposta prudente', CLARIFICATION_REQUIRED: 'Chiarimento richiesto', SOURCE_CONFLICT: 'Conflitto tra fonti', STALE_KNOWLEDGE: 'Conoscenza obsoleta', CONTENT_STALE: 'Contenuto obsoleto', INDEX_STALE: 'Indice obsoleto', EMBEDDING_STALE: 'Embedding obsoleto', REVIEW_OVERDUE: 'Revisione scaduta' });
Object.assign(CODE_LABELS.hu, { HIGH: 'Magas', MEDIUM: 'Közepes', LOW: 'Alacsony', NO_GROUNDED_ANSWER: 'Nem adható biztonságos válasz', CAUTIOUS_ANSWER: 'Óvatos válasz', CLARIFICATION_REQUIRED: 'Pontosítás szükséges', SOURCE_CONFLICT: 'Forrásütközés', STALE_KNOWLEDGE: 'Elavult tudás', CONTENT_STALE: 'Elavult tartalom', INDEX_STALE: 'Elavult index', EMBEDDING_STALE: 'Elavult embedding', REVIEW_OVERDUE: 'Lejárt ellenőrzés' });
Object.assign(CODE_LABELS.sv, { HIGH: 'Hög', MEDIUM: 'Medel', LOW: 'Låg', NO_GROUNDED_ANSWER: 'Kan inte svara säkert', CAUTIOUS_ANSWER: 'Försiktigt svar', CLARIFICATION_REQUIRED: 'Förtydligande krävs', SOURCE_CONFLICT: 'Källkonflikt', STALE_KNOWLEDGE: 'Inaktuell kunskap', CONTENT_STALE: 'Innehåll inaktuellt', INDEX_STALE: 'Index inaktuellt', EMBEDDING_STALE: 'Embedding inaktuell', REVIEW_OVERDUE: 'Granskning försenad' });
Object.assign(CODE_LABELS.fr, { HIGH: 'Élevée', MEDIUM: 'Moyenne', LOW: 'Faible', NO_GROUNDED_ANSWER: 'Réponse sûre impossible', CAUTIOUS_ANSWER: 'Réponse prudente', CLARIFICATION_REQUIRED: 'Précision requise', SOURCE_CONFLICT: 'Conflit de sources', STALE_KNOWLEDGE: 'Connaissance obsolète', CONTENT_STALE: 'Contenu obsolète', INDEX_STALE: 'Index obsolète', EMBEDDING_STALE: 'Embedding obsolète', REVIEW_OVERDUE: 'Révision en retard' });
Object.assign(CODE_LABELS.pl, { HIGH: 'Wysoka', MEDIUM: 'Średnia', LOW: 'Niska', NO_GROUNDED_ANSWER: 'Brak bezpiecznej odpowiedzi', CAUTIOUS_ANSWER: 'Ostrożna odpowiedź', CLARIFICATION_REQUIRED: 'Wymagane doprecyzowanie', SOURCE_CONFLICT: 'Konflikt źródeł', STALE_KNOWLEDGE: 'Nieaktualna wiedza', CONTENT_STALE: 'Nieaktualna treść', INDEX_STALE: 'Nieaktualny indeks', EMBEDDING_STALE: 'Nieaktualny embedding', REVIEW_OVERDUE: 'Zaległy przegląd' });
Object.assign(CODE_LABELS.cs, { HIGH: 'Vysoká', MEDIUM: 'Střední', LOW: 'Nízká', NO_GROUNDED_ANSWER: 'Nelze bezpečně odpovědět', CAUTIOUS_ANSWER: 'Opatrná odpověď', CLARIFICATION_REQUIRED: 'Je třeba upřesnění', SOURCE_CONFLICT: 'Konflikt zdrojů', STALE_KNOWLEDGE: 'Zastaralé znalosti', CONTENT_STALE: 'Zastaralý obsah', INDEX_STALE: 'Zastaralý index', EMBEDDING_STALE: 'Zastaralý embedding', REVIEW_OVERDUE: 'Kontrola po termínu' });

export function supportAdminCodeLabel(language: PortalUiLanguage, code: string): string {
  const translated = CODE_LABELS[language]?.[code];
  if (translated) return translated;
  return code.toLowerCase().split('_').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ');
}
