-- Backfill product/site changes from the active implementation week.
-- Source of truth: Git commits from 2026-08-24 through 2026-08-26.
-- All entries stay internal with status='new'. Nothing is auto-published.

insert into public.site_change_entries (
  source,
  source_ref,
  implemented_at,
  title_internal,
  description_internal,
  technical_description,
  title_public,
  description_public,
  module,
  change_type,
  affected_roles,
  user_impact_score,
  technical_impact_score,
  publish_recommendation,
  is_important,
  status
)
select
  v.source,
  v.source_ref,
  v.implemented_at::timestamptz,
  v.title_internal,
  v.description_internal,
  v.technical_description,
  v.title_public,
  v.description_public,
  v.module,
  v.change_type,
  v.affected_roles,
  v.user_impact_score,
  v.technical_impact_score,
  v.publish_recommendation,
  v.is_important,
  'new'
from (
  values
    (
      'git-backfill',
      'week-2026-08-24:partner-map-plz2',
      '2026-08-25 12:00:00+00',
      'Germany PLZ2 partner map overlay',
      'Partner Map kan vise Tyskland opdelt i Postleitzahl-Leitregionen / PLZ2 med ca. 95 tocifrede postnummerområder.',
      'Bekræftet af commits de6cbd97, eb3591fe, bc97c72e, aabf1d63 og 5f122e38.',
      'Nyt postnummerkort for Tyskland',
      'Partnerkortet kan nu vise Tyskland opdelt i PLZ2-postnummerområder, så dækning og områder kan vurderes mere præcist.',
      'map',
      'feature',
      array['timan_backend','timan_seller']::text[],
      7,
      6,
      'maybe',
      false
    ),
    (
      'git-backfill',
      'week-2026-08-24:partner-map-geocoding',
      '2026-08-25 13:00:00+00',
      'Partner Map geocoding and missing-coordinate handling',
      'Forhandlerkortet har fået bedre geocoding, tydeligere advarsler ved manglende koordinater og bedre fallback for adresser.',
      'Bekræftet af commits 81c02f61 og 708138d1.',
      'Bedre adresseplacering på partnerkortet',
      'Partnerkortet håndterer nu forhandleradresser og manglende koordinater tydeligere.',
      'map',
      'improvement',
      array['timan_backend','timan_seller']::text[],
      5,
      6,
      'maybe',
      false
    ),
    (
      'git-backfill',
      'week-2026-08-24:carto-runtime-config',
      '2026-08-26 18:00:00+00',
      'CARTO basemap runtime config',
      'CARTO basemap key læses nu som public runtime config, så Standard og Mørk kan fungere uden Lovable Enterprise Build Secrets.',
      'Bekræftet af commits eb3ed421, 6c1dc588 og 20aa182a.',
      'Standard og Mørk kort er stabiliseret',
      'Partnerkortets Standard og Mørk kortlag kan nu indlæses via public runtime-konfiguration.',
      'map',
      'fix',
      array['timan_backend','timan_seller']::text[],
      6,
      6,
      'maybe',
      false
    ),
    (
      'git-backfill',
      'week-2026-08-24:messe-lead-flow',
      '2026-08-26 11:00:00+00',
      'Messeformular og messe lead-flow',
      'Messe-flowet er forbedret med lead-oprettelse, ordre/tilbud-flow, kontaktoplysninger, visitkort/billede og mail-flow.',
      'Bekræftet af commits fe600bcb, d191ab0e, d2dfd99b, c00483b7, 16e21382 og 8dddeaa1.',
      'Messeformularen er klar til brug på messer',
      'Leads og kontaktoplysninger kan registreres mere sikkert og effektivt direkte fra messen.',
      'messe',
      'feature',
      array['timan_backend','timan_seller','timan_messe']::text[],
      9,
      7,
      'publish',
      true
    ),
    (
      'git-backfill',
      'week-2026-08-24:messe-brochures',
      '2026-08-26 10:00:00+00',
      'Messe brochure page flip',
      'Messe-portalen har fået mere realistisk brochurevisning med touch/page-flip.',
      'Bekræftet af commits c845d543 og 933ffa26.',
      'Brochurer kan bladres mere naturligt',
      'Brochurevisningen i messeportalen er gjort mere levende og touch-venlig.',
      'messe',
      'improvement',
      array['timan_messe','timan_seller']::text[],
      6,
      4,
      'maybe',
      false
    ),
    (
      'git-backfill',
      'week-2026-08-24:timan-2620-viewer',
      '2026-08-26 09:00:00+00',
      'Timan 2620 viewer and trial flow improvements',
      'Timan 2620-visningen og afprøvningsflowet er forbedret med bedre billeder, hotspots, udstyrsskift og backend-register.',
      'Bekræftet af commits 48c10149, c17e4ca3, 6bf11f55, 69abcc7b, 1e3bc6cf og 6e7c7f93.',
      'Timan 2620 er forbedret visuelt',
      'Timan 2620-visningen er gjort mere præcis med bedre billeder, hotspots og udstyrsvalg.',
      'messe',
      'feature',
      array['timan_backend','timan_seller','timan_messe']::text[],
      8,
      7,
      'publish',
      false
    ),
    (
      'git-backfill',
      'week-2026-08-24:crm-leads-overview',
      '2026-08-26 12:00:00+00',
      'CRM Leads overview, filters and active lead consistency',
      'CRM Leads er forbedret med follow-up filtre, leadnummer-søgning, badges, sortering og samlet aktiv lead/demo-lead logik.',
      'Bekræftet af commits c4c8881a, f4ebb31b, 97081bb7, 2f4533c6, 77bab453, eb2a7280, a2901006, aabc30e8, d89d961b, 331f39a2, 8ad420a4 og 9f8133d7.',
      'Leads er nemmere at finde og følge op på',
      'CRM Leads har fået bedre filtre, søgning og opfølgningsvisning, så sælgere hurtigere kan se hvad der kræver handling.',
      'crm',
      'feature',
      array['timan_backend','timan_seller']::text[],
      8,
      7,
      'publish',
      true
    ),
    (
      'git-backfill',
      'week-2026-08-24:crm-attachments-private-storage',
      '2026-08-24 14:00:00+00',
      'CRM lead attachments in private storage',
      'CRM lead-vedhæftninger gemmes i privat storage og vises i leadflowet.',
      'Bekræftet af commit 5dddcca4.',
      'Vedhæftninger på leads er gjort mere sikre',
      'Lead-billeder og filer håndteres nu i privat storage.',
      'crm',
      'improvement',
      array['timan_backend','timan_seller']::text[],
      6,
      8,
      'maybe',
      false
    ),
    (
      'git-backfill',
      'week-2026-08-24:external-crm-scope',
      '2026-08-26 14:00:00+00',
      'Scoped CRM for external portal roles',
      'Eksterne forhandler-, importør- og servicepartnerroller kan få scoped CRM-visning, hvor data filtreres til deres relevante forhandlerrelationer.',
      'Bekræftet af commits 336d6073, 68b16a18, 04b04908 og 594e6957.',
      'Forhandlere kan se egne CRM- og forhandlerdata',
      'Forhandlerdata og CRM-visninger kan nu åbnes mere målrettet for eksterne roller og samarbejdspartnere.',
      'dealer_data',
      'feature',
      array['timan_backend','timan_seller','timan_dealer','timan_importer','timan_service_partner','dealer_user']::text[],
      9,
      8,
      'publish',
      true
    ),
    (
      'git-backfill',
      'week-2026-08-24:backend-seller-view-as',
      '2026-08-26 15:00:00+00',
      'Backend seller view-as and dealer overview fixes',
      'Backend kan skifte mellem sælgere og se relevante forhandleroverblik, mens enkelt sælger-visning holdes scoped.',
      'Bekræftet af commits f237f7de, 93ed98f2, c52fe3ff og 04b04908.',
      'Backend kan nemmere kontrollere sælgerdata',
      'Backend-overblikket gør det lettere at skifte mellem sælgere og kontrollere deres forhandlere.',
      'backend',
      'improvement',
      array['timan_backend']::text[],
      5,
      6,
      'internal',
      false
    ),
    (
      'git-backfill',
      'week-2026-08-24:news-cms-translation-typography',
      '2026-08-26 13:00:00+00',
      'News CMS translation and typography improvements',
      'News CMS har fået automatisk sprogsynk, dynamisk oversættelsesfunktion, typography controls og Template 05-rettelser.',
      'Bekræftet af commits 65049862, 56a7e594, 46522462, d1fe4c00, e89872fb og 79b586ad.',
      'Nyheder er nemmere at oversætte og tilpasse',
      'Marketing kan arbejde bedre med sprog, typografi og visning i nyhedsskabeloner.',
      'marketing',
      'feature',
      array['timan_backend']::text[],
      8,
      7,
      'publish',
      false
    ),
    (
      'git-backfill',
      'week-2026-08-24:site-feature-changelog',
      '2026-08-26 17:00:00+00',
      'Marketing site feature changelog',
      'Marketing → Nye features på sitet er oprettet med intern kø, filtrering, redigering, impact, anbefaling og publiceringskontrol.',
      'Bekræftet af commit c6b99e8d og live migration 20260826210851.',
      'Nye features kan gennemgås før publicering',
      'Marketing kan nu gennemgå ændringer på sitet og vælge hvad der skal vises under Hvad er nyt?',
      'marketing',
      'feature',
      array['timan_backend']::text[],
      7,
      8,
      'maybe',
      false
    ),
    (
      'git-backfill',
      'week-2026-08-24:tsb-preview-reset',
      '2026-08-26 16:00:00+00',
      'TSB portal preview data reset',
      'TSB preview/testdata for TSB’er og maskiner blev ryddet, så portalen kan starte frisk.',
      'Bekræftet af commit 1d260287.',
      'TSB-portalen er nulstillet for testdata',
      'Gamle preview-data er ryddet, så TSB-området kan bruges fra et friskere udgangspunkt.',
      'tsb',
      'improvement',
      array['timan_backend','timan_service']::text[],
      4,
      4,
      'internal',
      false
    ),
    (
      'git-backfill',
      'week-2026-08-24:warranty-registration-sync',
      '2026-08-25 15:00:00+00',
      'Warranty registration schema and scoped views',
      'Garantiregistrering har fået databasegrundlag, SharePoint-sync forbedringer, resultatoverblik og scoped visning for forhandlerbrugere.',
      'Bekræftet af commits 45212c4b, fcddb22c, 236ec178 og 47908edb.',
      'Garantiregistrering er forbedret',
      'Warranty-data kan håndteres mere struktureret og vises mere korrekt for relevante brugere.',
      'warranty',
      'feature',
      array['timan_backend','timan_service','timan_dealer','dealer_user']::text[],
      7,
      8,
      'maybe',
      false
    )
) as v (
  source,
  source_ref,
  implemented_at,
  title_internal,
  description_internal,
  technical_description,
  title_public,
  description_public,
  module,
  change_type,
  affected_roles,
  user_impact_score,
  technical_impact_score,
  publish_recommendation,
  is_important
)
where not exists (
  select 1
  from public.site_change_entries existing
  where existing.source_ref = v.source_ref
);
