alter table public.dealer_accounts
  add column if not exists director_name text,
  add column if not exists invoice_email text,
  add column if not exists finance_contact_name text,
  add column if not exists finance_contact_phone text,
  add column if not exists finance_contact_email text,
  add column if not exists social_facebook text,
  add column if not exists social_linkedin text,
  add column if not exists social_tiktok text,
  add column if not exists social_youtube text,
  add column if not exists social_instagram text,
  add column if not exists sales_contact_name text,
  add column if not exists sales_contact_phone text,
  add column if not exists sales_contact_email text,
  add column if not exists sales_has_multiple boolean not null default false,
  add column if not exists workshop_contact_name text,
  add column if not exists workshop_contact_phone text,
  add column if not exists workshop_contact_email text,
  add column if not exists workshop_has_multiple boolean not null default false,
  add column if not exists marketing_contact_name text,
  add column if not exists marketing_contact_phone text,
  add column if not exists marketing_contact_email text,
  add column if not exists payment_terms text,
  add column if not exists currency_code text;
